### ISSUE TITLE
Move Spider to an add-on

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#3113]
Tasks:
 - [x] Migrate #7299 once merged.
     - Done in zaproxy/zap-extensions#3886
 - [x] Migrate #7356 and #7414 once merged.
     - Done in zaproxy/zap-extensions#3945 
 - [x] Ensure spider classes are all using parameterized logging (vs concatenation), and adjust class names so that acronyms aren't full caps (Uri vs URI, etc).
    - Done in zaproxy/zap-extensions#3888
 - [x] Migrate existing add-ons to use the spider from the add-on:
    - [x] Automation (Done in zaproxy/zap-extensions#3962)
    - [x] Form Handler (Superseded with zaproxy/zap-extensions#3954)
    - [x] GraqhQL (Done in https://github.com/zaproxy/zap-extensions/pull/3953 and zaproxy/zap-extensions#3955)
    - [x] OpenAPI (Done in https://github.com/zaproxy/zap-extensions/pull/3920)
    - [x] Quick Start (Done in zaproxy/zap-extensions#3972)
    - [x] SOAP (Done in https://github.com/zaproxy/zap-extensions/pull/3952)
 - [x] Use Form Handler add-on (Done in zaproxy/zap-extensions#3959)
 - [x] Merge #7335 once all above tasks done.
 - [x] Change `SpiderParam` to extend `VersionedAbstractParam`. (Done in zaproxy/zap-extensions#3976)
 - [x] Include spider add-on in weekly releases. (Done in zaproxy/zaproxy#7335)
 - [x] Add to zap-admin's allow list for website help pages. (Done in https://github.com/zaproxy/zap-admin/pull/809)
 - [x] Complete zaproxy/zaproxy#4398
     - [x] Migrate the code to the add-on. zaproxy/zap-extensions#3991
 - [x] Remove core SQLite dependency (#7473).
   - [x] Move SQLite to an add-on and change spider to use it (zaproxy/zap-extensions#4067).
 - [x] Update the HUD to use the "new" event publisher. (Done in zaproxy/zap-hud#1141)
 - [x] Update 2.12 release notes to mention the migration. (Done in https://github.com/zaproxy/zap-core-help/pull/460)
 - [x] Update add-on changelog and 2.12 release notes to mention the changes compared to 2.11 spider. (Done in https://github.com/zaproxy/zap-extensions/pull/4081)
 - [x] Remove the code that checks if the old extension is present (coreSpiderDisabled glue code) (zaproxy/zap-extensions#4129).
 - [x] update ui.tabs.spider in the hook to use the add-on map key (zaproxy/zap-extensions#4129).
 - [x] Update build to release to Maven Central (zaproxy/zap-extensions#4124).
 - [ ] Post add-on release tasks:
    - [ ] Include spider add-on in main releases.
    - [ ] Change (website) core help pages to link to add-on help pages.

---
Move the (traditional) spider to an add-on. Main reason to move it is that it allows to release enhancements and bug fixes sooner and more often (no longer requires releasing a whole new version of ZAP).

No core functionality depends on the Spider. Existing add-ons that extend the Spider (e.g. custom parsers/filters) will have to be changed to depend on the new add-on (e.g. for proper un/installation).

**Comment by kingthorin** [comment]
This could be moved to the newly added Spider add-on: https://github.com/zaproxy/zap-extensions/tree/main/addOns/spider

If/when it is then the existing parsers UnitTests should be enhanced to check parsed/returned URLs: https://github.com/zaproxy/zap-extensions/pull/3474#discussion_r796281993

**Comment by thc202** [comment]
There are ongoing PRs to the spider parsers though.

**Comment by kingthorin** [comment]
It's okay, it won't be instant.

**Comment by kingthorin** [comment]
Dev group announcement: https://groups.google.com/g/zaproxy-develop/c/51Kv1re45l8

**Comment by thc202** [comment]
Do we still want to release the Spider add-on to 2.11 (for the SVG parser)?

**Comment by psiinon** [comment]
Would it be used?? I was assuming 2.11 would still use the core spider...

**Comment by thc202** [comment]
For 2.11 it provides the SVG parser, for 2.12/weekly the whole spider.

**Comment by kingthorin** [comment]
From IRC here's my take:
> Well we've maintained for years that we only support current release
> I don't think the SVG parser is a huge benefit or miss for anyone that hangs onto 2.11 a little long

**Comment by kingthorin** [comment]
> Update build to release to Maven central?

Essentially the same as is done for commonlib?
https://github.com/zaproxy/zap-extensions/blob/main/addOns/commonlib/commonlib.gradle.kts

**Comment by thc202** [comment]
Yes, but better avoid duplicating in each add-on and move the configuration to the `addOns` project.

**Comment by thc202** [comment]
Closing, the move is complete, the other tasks will be done with the release of 2.12.

**Comment by kingthorin** [comment]
Yay!!!!
