### ISSUE TITLE
Packaged script tracker

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3566]
Changes proposed for packaged scripts like the zap-baseline.py and zap-api-scan.py

- [ ] Extract common features to a common script
- [ ] Control ascan rules via the config file
- [ ] Control strength and threshold via the config file
- [ ] Implement a new zap-full-scan.py script
- [ ] Use [argparse](https://docs.python.org/2/library/argparse.html) instead of getops (as per suggestion in #3561)
- [ ] Support python 3 as well as 2

**Comment by psiinon** [comment]
Removed 

* Control ascan rules via the config file
* Control strength and threshold via the config file

From first comment - no longer relevant with the move to the Automation Framework.
