### ISSUE TITLE
Update add-ons to use new Import menu 

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3578]
We are getting more and more Import* options under the Tools menu.
I suggest we introduce a Tools / Import submenu (or top level Import menu?) for things like:

- [x] Import files containing URLs add-on zaproxy/zap-extensions#1963
  - Import a file containing URLs
- [x] Log File Importer add-on zaproxy/zap-extensions#1964
  - Import Logs into Zap Site Tree...
- [x] OpenAPI Support add-on zaproxy/zap-extensions#1964
  - Import an OpenAPI Definition file from the local system
  - Import an OpenAPI Definition file from a URL
- [x] SOAP Scanner add-on zaproxy/zap-extensions#1964
  - Import a WSDL file from the local system
  - Import a WSDL file from a URL

There should be some coordination so that these all happen at a similar time

**Comment by thc202** [comment]
Another menu item "Import Logs into Zap Site Tree..." (which is currently in Analyse).

**Comment by kingthorin** [comment]
I like this idea. 

- Include Context Import?
- Do we also need an Export menu/sub-menu to unify those items as well? (There are definitely fewer: Context, and various URL export options...)

**Comment by psiinon** [comment]
I kind of think Context Import is more of a File menu type of thing? But happy to be persuaded otherwise.
So move all of the Report / Export* items to a top level Export menu? That would probably make more sense

**Comment by Yashvendra** [comment]
I would like to work on this issue since I'm also preparing for GSoC 2019, I would really appreciate any help on where should I start digging.

**Comment by Yashvendra** [comment]
Hey, I am working on this issue, I made a new top level `Import` Menu. So only the task remaining is to successfully change this `getHookMenu().addToolsMenuItem()` to `getHookMenu().addImportMenuItem()` for each Import Item.

But I want to ask that how will I be able to test it? I have `Zap-extensions` master branch as added module in my `Zaproxy` project, but  [ExtensionImportUrls.java](https://github.com/Yashvendra/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/importurls/ExtensionImportUrls.java) is in beta branch so from my understanding I would have to clone `Zap-extensions` beta branch and then add this local repo as module to my `zaproxy` project . After making changes to the respective files, it should appear dynamically in the application  or would I have to build something using ant? 
 
I know this is a newbie doubt but I'm new to this code base so please help me out @thc202 @kingthorin @psiinon .

**Comment by thc202** [comment]
Issue updated to change the add-ons to use the new menu.

**Comment by Yashvendra** [comment]
Hello guys, add ons have been updated to use Import menu.
![Screenshot from 2019-03-29 02-32-41](https://user-images.githubusercontent.com/23001311/55192837-81d5e380-51cb-11e9-9b6a-0d56eccdec49.jpg)

**Comment by thc202** [comment]
Thanks! Leaving this open until we merge the PRs.

**Comment by thc202** [comment]
Closing, PRs were merged.
