### ISSUE TITLE
Retire.js add-on issues tracker

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3742]
Tracker issues for changes we'd like to see to https://github.com/h3xstream/burp-retire-js#zap-plugin
Feel free to add to this list...

- [ ] Use ZAP code to retrieve config file - so that it works with fwd proxy + appears in History
- [x] Rename alerts to be more consistent with others, eg "JavaScript library with known vulnerabilities" [ ~~Edit: This seems to have been raised and partially addressed upstream: h3xstream/burp-retire-js#30~~ Edit 2: This has been fixed upstream: h3xstream/burp-retire-js#40 ]
- [ ] Add help
- [x] Include evidence in alerts [Fixed in h3xstream/burp-retire-js#57]
- [ ] Correct version declared in ZapAddOn.xml file
- [x] Return correct ID in the plugin [zaproxy/zaproxy#3732]

**Comment by kingthorin** [comment]
There's also this: https://github.com/nikmmy/retire/ which might be easier to adapt since it's already ZAP'ified and not trying to handle two platforms.

**Comment by psiinon** [comment]
That looks interesting, although it hasnt been updated for a long time

**Comment by kingthorin** [comment]
Is the intent of this tracker to have the plugin brought into the alpha branch and modified or to submit changes to @h3xstream?

**Comment by psiinon** [comment]
Whichever is the most sustainable long term?

**Comment by thc202** [comment]
IMO leave it in the current repo and submit changes (or raise issues).

Is there any major issue that would prevent the add-on from being released to marketplace as is? (I think the version in the manifest might need to be tweaked again but other than that it's looks ok to me.)

**Comment by kingthorin** [comment]
Maybe just the first bullet? Probably poor form for requests to be made that aren’t obvious to the user..... I’ll have a look at things as time permits.

**Comment by kingthorin** [comment]
Re: Alert names are we good with this format?
https://github.com/h3xstream/burp-retire-js/pull/35

Ex: It has one variable (the library name) instead of two.

**Comment by thc202** [comment]
LGTM.

**Comment by thc202** [comment]
Regarding the first bullet, I'm fine going as is for a first release.

**Comment by kingthorin** [comment]
A zaproxy variant has been created and released: https://github.com/zaproxy/zap-extensions/tree/master/addOns/retire
