### ISSUE TITLE
Browser launch tracker

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3789]
The changes to allow ZAP to launch browsers proxing through ZAP are more involved than orriginally anticipated ;)
The tasks are:

- [x] Rename Open in Browser popup #3760 
- [x] Update Chromedriver 2.31, Geckodriver v0.18.0, IEDriverServer 3.4.0 libs zaproxy/zap-libs#8
- [x] Add initial HTML content file zaproxy/zap-admin/pull/9
- [x] Update webdriver extensions zaproxy/zap-extensions/pull/981
- [x] Support latest selenium addon zaproxy/zap-extensions#958
- [x] Add options for launching browsers proxying through ZAP zaproxy/zap-extensions#956
- [x] Update Quick Start to use optional extensions (included in zaproxy/zap-extensions#956)
- [x] Update Selenium library to version 3.x #3509
   - [x] Update Zest to use Selenium 3.4.0 mozilla/zest#111
   - [x] Update Crawljax to use Selenium 3.4.0 zaproxy/crawljax/pull/4
- [x] Changes to support launching proxied browsers zaproxy/zap-extensions#957
- [x] Include in weekly release
- [x] Publish add-ons on the Marketplace for 2.6.0 (using Java 8)

The add-ons that will need to be released at the same time are:

- selenium
- quickstart
- zest
- spiderAjax
- jxbrowser
- jxbrowserlinux32
- jxbrowserlinux64
- jxbrowsermacos
- jxbrowserwindows
- webdriverlinux 
- webdrivermacos
- webdriverwindows
- domxss

~~More tasks and add-ons may be added ;)~~

**Comment by psiinon** [comment]
Changes complete :)
These will all be included in the weekly release I'm generating now.
We just need to decide when to release the add-ons - now or after the weekly has been out for a few days to sanity check that everything seems ok?

**Comment by thc202** [comment]
Give it some days? We should also post to mailing lists to inform that the new versions will require Java 8(?).

**Comment by kingthorin** [comment]
Ya a few days is probably the best move.

**Comment by kingthorin** [comment]
We need to update all the build files for Java 8 too, right? https://github.com/zaproxy/zap-extensions/blob/master/build/build.xml#L5

**Comment by thc202** [comment]
It's not necessary (for now), those add-ons are not using Java 8 features it's just the dependencies that require the newer version.

**Comment by kingthorin** [comment]
Ok, thought we were switching everything...

**Comment by psiinon** [comment]
We will, but just before we release 2.7.0.
Otherwise we cant release any Java 7 addons for 2.6.0 (which these ones arent;)

**Comment by kingthorin** [comment]
Gotcha

**Comment by thc202** [comment]
Closing, new versions of the add-ons are already available in the marketplace.
