### ISSUE TITLE
Update all resources to use new logo

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#4024]
The images in src can be updated now (I'll issue a PR for those soon) while the others should probably only be updated when we release 2.7.0
This is a tracker issue for us to, er, keep track of them all :)

- [x] https://github.com/zaproxy/zaproxy/tree/develop/src/resource (#4025)
  - [x] Regenerate `ZAP.icns` (#4075)
- [x] User Guide (JavaHelp) (zaproxy/zap-core-help#142)
- [x] Quick Start add-on (zaproxy/zap-extensions#1135)
- [x] Getting Started Guide (zaproxy/zap-extensions#1136)
- [x] https://github.com/zaproxy
- [x] https://github.com/zaproxy/zaproxy#-owasp-zap
- [x] https://github.com/zaproxy/zap-core-help#-owasp-zap-user-guide
- [x] https://www.owasp.org/index.php/ZAP
- [x] https://www.owasp.org/index.php/OWASP_Zed_Attack_Proxy_Project#tab=Screenshots [20220517 - Marking complete, no longer applicable]
- [x] https://zaproxy.blogspot.com/
- [x] https://crowdin.com/project/owasp-zap
- [x] https://www.youtube.com/playlist?list=PLEBitBW-Hlsv8cEIUntAO8st2UGhmrjUB
- [x] https://twitter.com/zaproxy
- [x] https://www.openhub.net/p/zaproxy
- [x] https://www.bountysource.com/teams/zap/issues
- [x] https://bugcrowd.com/owaspzap
- [x] https://github.com/zaproxy/zap-swag - loads to do here!
- [x] http://zapbot.github.io/zap-mgmt-scripts/index.html
- [x] http://www.zaproxy.org/ (if its not the new website) [20220517 - We are and have been using the new site for quite a while]

Please add to this list as you spot other places!

**Comment by kingthorin** [comment]
Is there anything for:
zapbot?
github.io?

**Comment by psiinon** [comment]
Added :)

**Comment by kingthorin** [comment]
I think the only thing remaining in the swag repo is the T-Shirts (I couldn't view the *.icns file so I'm not sure if it was replaced ... hopefully it is in sync with the icns task mentioned above).

**Comment by kingthorin** [comment]
Closing all tasks complete
