### ISSUE TITLE
2.7.0 RC Issues tracker

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#4032]
Tracker bug for issues with the 2.7.0 RC releases.
Minor issues don't necessarily need a separate bug, they can just be recorded here.

- [x] Finish Java 8 changes #3470 
- [x] Help icons still old ones #4024 #4035 
- [x] Change help to not use the term 'intercepting proxy' #3980 
- [x] Main proxy with `0.0.0.0` is changed to specific IP address when changing options #4034
- [x] MultiProxy Logging Discrepancy #4039
- [x] Add Scroll Pane for Multiproxy #4040
- [x] Correct key used when adding proxy through the API #4042
- [x] History tab cleared when session persisted #3207 (Fix PR https://github.com/zaproxy/zaproxy/pull/4046)
- [x] Use main connection settings in additional proxies #4050
- [x] Apply proxy options to additional proxies #4057
- [x] Honour proxy exclusions in additional proxies #4062

**Comment by psiinon** [comment]
ok, so #3470 isnt quite finished, but the remaining tasks can be done post release
