### ISSUE TITLE
[FrontEndScanner] Phase 1 tracker

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#4939]
Changes needed prior to first release, eg in the weekly releases.

- [x] Basic user help zaproxy/zap-extensions#1917
- [x] Dont use inline JS #4894 
- [x] Use button instead of menu item to enable/disable zaproxy/zap-extensions#1779
- [x] Store enabled state in properties so it can be set on the cmdline zaproxy/zap-extensions#1780
- [ ] Address #4893.
- [ ] Add more scan rules?

The first release will just support passive scanning. Another tracker could be created once this is complete to cover active scanning.

Feel free to add to this list...

**Comment by psiinon** [comment]
Any other suggestions @Pamplemousse ?

**Comment by Pamplemousse** [comment]
About the "basic user help" item: is it what should be available via the help menu in ZAP's UI?

What about having a page in the [zap-extensions wiki](https://github.com/zaproxy/zap-extensions/wiki/) as well?

**Comment by thc202** [comment]
Yes, for example, https://github.com/zaproxy/zap-extensions/tree/master/src/org/zaproxy/zap/extension/ascanrules/resources/help

The wiki pages are generated from the help pages.

**Comment by thc202** [comment]
Reopening per talks in IRC, issue description updated with new tasks.

**Comment by Pamplemousse** [comment]
Following discussions on IRC, and after some information gathering, I do have one suggestion before releasing:
**Ensure it works**: Sadly the example script might be broken in its current state.

Hopefully, it can be fixed in a straightforward fashion.

**Comment by kingthorin** [comment]
I support this ^ plan 😉
