### ISSUE TITLE
ZAP failing Nexus scan

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#5221]
As per https://groups.google.com/d/msg/zaproxy-users/uMVYmtW_fko/tVBkk2gfFwAJ

- [ ] sonatype-2007-0004 apache-httpclient : commons-httpclient : 3.1 Open
- [x] CVE-2014-0114 commons-beanutils : commons-beanutils : 1.8.3 Open #5381
- [x] sonatype-2017-0359 org.apache.httpcomponents : httpclient : 4.5 Open #4794
- [x] CVE-2016-1000338 org.bouncycastle : bcprov-jdk15on : 1.52 Open #5381
- [x] CVE-2016-1000340 org.bouncycastle : bcprov-jdk15on : 1.52 Open #5381
- [x] CVE-2016-1000342 org.bouncycastle : bcprov-jdk15on : 1.52 Open #5381
- [x] CVE-2016-1000343 org.bouncycastle : bcprov-jdk15on : 1.52 Open #5381
- [x] CVE-2016-1000344 org.bouncycastle : bcprov-jdk15on : 1.52 Open #5381

It looks like we're still using at least some of those libs so we should look into this for 2.8.0

**Comment by thc202** [comment]
This could merged into #4780?

**Comment by kingthorin** [comment]
Edited title, [Sonatype Nexus](https://www.sonatype.com/appscan) != [Tenable Nessus](https://www.tenable.com/products/nessus/nessus-professional).

**Comment by psiinon** [comment]
I think its worth explicitly flagging these as they could prevent a lot of people using ZAP.

**Comment by thc202** [comment]
Closing, all items except one is done, the last will be addressed as part of #1765.
