### ISSUE TITLE
Merge zap-extensions' branches

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#5302]
Tracker issue for merge of zap-extensions' branches, beta and alpha into master.
Before the merge each branch will be changed to build the add-ons with [Gradle](https://gradle.org/), also, as part of the build changes the add-ons will be restructured (easier to merge later).

Tasks:
 - [x] Build add-ons with Gradle:
   - [x] master zaproxy/zap-extensions#1972
   - [x] beta zaproxy/zap-extensions#1973
   - [x] alpha zaproxy/zap-extensions#1974
 - [x] Merge beta into master zaproxy/zap-extensions#1975
 - [x] Merge alpha into master zaproxy/zap-extensions#1977
 - [x] Update zaproxy build and Docker live image #5293
 - [x] Update open pull requests
 - [x] Delete beta and alpha branches (and corresponding branch protection rules)
 - [x] Update documentation and fix broken links:
    - [x] community-scripts zaproxy/community-scripts#151
    - [x] open issues (e.g. promotion)
    - [x] wikis
       - [x] zap-extensions https://github.com/zaproxy/zap-extensions/wiki/_compare/fdaf894%5E...fdaf894
       - [x] zaproxy https://github.com/zaproxy/zaproxy/wiki/_compare/1a6013c%5E...1a6013c
    - [x] blog
    - [ ] ?

##  Add-On Structure

The files (e.g. main/test source code, resources) of the add-ons will be relocated to be in its own project/directory, to make the add-ons self contained and independent from each other (preventing issues like #5262).

### Directory Layout

The (typical) add-on directory layout will be:
```
.
├── CHANGELOG.md
├── <addOnId>.gradle.kts
└── src
    ├── main
    │   ├── java
    │   ├── javahelp
    │   ├── resources
    │   └── zapHomeFiles
    └── test
        ├── java
        └── resources
```
- `CHANGELOG.md` - the changelog of the add-on;
- `<addOnId>.gradle.kts` - Gradle build file of the add-on, with the project and add-on configuration (e.g. manifest, dependencies);
- `main/java` - main (Java) source code of the add-on;
- `main/javahelp` - add-on help, in JavaHelp format, default language (English) and translations;
- `main/resources` - main resources (e.g. images/icons, Messages.properties);
- `main/zapHomeFiles` - files to be deployed to ZAP home directory;
- `test/java` - test (Java) source code;
- `test/resources` - test resources.

While the example shows just the directories for Java source code it's possible to use other JVM languages (e.g. Groovy, Kotlin).

### Manifest

The manifests (`ZapAddOn.xml`) will be removed, the manifest will be automatically generated when the add-on is built, based on the add-on configuration (build file and other files present in project).

Example add-on configuration (from build file of Access Control add-on):
```
zapAddOn {
    addOnName.set("Access Control Testing")
    zapVersion.set("2.7.0")

    manifest {
        author.set("ZAP Dev Team")
    }
}
```

By default the manifest will be generated with the version and description of the project, the build will automatically check the classpath of the add-on for extensions and active/passive scanners to include in the manifest. The files placed in the `zapHomeFiles` directory will be automatically added to the `files` of the manifest.
This avoids the need to manually manage the declared entries, which was sometimes forgotten.

The `changes` of the manifest will be read from the changelog (`CHANGELOG.md`).

### Dependencies

The [dependencies are managed by Gradle](https://docs.gradle.org/current/userguide/introduction_dependency_management.html), simply [declare them](https://docs.gradle.org/current/userguide/declaring_dependencies.html) in the respective build file.
The dependencies should be obtained from a remote repository (e.g. Maven Central) whenever possible, only as last resort should they be added to the zap-extensions repository (to avoid increase the size of the repository even more).

## Project Structure

The add-ons will be located in the `addOns` directory and the test utilities will be moved to its own project.

The resulting project structure:
```
Root project 'zap-extensions'
+--- Project ':addOns' - Common configuration of the add-ons.
|    +--- Project ':addOns:accessControl' - Adds a set of tools for testing access control in web applications.
|    +--- Project ':addOns:alertFilters' - Allows you to automate the changing of alert risk levels.
|    +--- Project ':addOns:alertReport' - Allows you to generate reports for alerts you specify in pdf or odt format
|    +--- Project ':addOns:amf' - Adds support for AMF messages
|    +--- Project ':addOns:ascanrules' - The release quality Active Scanner rules
|    +--- Project ':addOns:ascanrulesAlpha' - The alpha quality Active Scanner rules
|    +--- Project ':addOns:ascanrulesBeta' - The beta quality Active Scanner rules
|    +--- Project ':addOns:authstats' - Records logged in/out statistics for all contexts in scope.
|    +--- Project ':addOns:beanshell' - Provides a BeanShell Console
|    +--- Project ':addOns:birtreports' - Alert reports using BIRT report API
|    +--- Project ':addOns:browserView' - Adds an option to render HTML responses like a browser
|    +--- Project ':addOns:bruteforce' - Forced browsing of files and directories using code from the OWASP DirBuster tool
|    +--- Project ':addOns:bugtracker' - Bug Tracker extension.
|    +--- Project ':addOns:callgraph' - Allows the user to view a call graph of the selected resources
|    +--- Project ':addOns:cmss' - Fingerprint web applications
|    +--- Project ':addOns:codedx' - Includes request and response data in XML reports and provides the ability to upload reports directly to a Code Dx server
|    +--- Project ':addOns:coreLang' - Translations of the core language files
|    +--- Project ':addOns:cspscanner' - Content Security Policy (CSP) Scanner
|    +--- Project ':addOns:customreport' - New HTML report module allows users to customize report content.
|    +--- Project ':addOns:diff' - Displays a dialog showing the differences between 2 requests or responses. It uses diffutils and diff_match_patch
|    +--- Project ':addOns:directorylistv1' - List of directory names to be used with "Forced Browse" add-on.
|    +--- Project ':addOns:directorylistv2_3' - Lists of directory names to be used with "Forced Browse" add-on.
|    +--- Project ':addOns:directorylistv2_3_lc' - Lists of lower case directory names to be used with "Forced Browse" add-on.
|    +--- Project ':addOns:domxss' - DOM XSS Active scanner rule
|    +--- Project ':addOns:exportreport' - Report Export module that allows users to customize content and export in a desired format.
|    +--- Project ':addOns:formhandler' - This Form Handler Add-on allows a user to define field names and values to be used in a form's fields. Fields can be added, modified, enabled, and deleted for use in form fields.
|    +--- Project ':addOns:frontendscanner' - Scan modern web applications relying heavily on Javascript.
|    +--- Project ':addOns:fuzz' - Advanced fuzzer for manual testing
|    +--- Project ':addOns:fuzzdb' - FuzzDB files which can be used with the ZAP fuzzer
|    +--- Project ':addOns:gettingStarted' - A short Getting Started with ZAP Guide
|    +--- Project ':addOns:groovy' - Adds Groovy support to ZAP
|    +--- Project ':addOns:highlighter' - Allows you to highlight strings in the request and response tabs.
|    +--- Project ':addOns:httpsInfo' - Displays HTTPS configuration information.
|    +--- Project ':addOns:imagelocationscanner' - Image Location and Privacy Passive Scanner
|    +--- Project ':addOns:importLogFiles' - Allows you to import log files from ModSecurity and files previously exported from ZAP
|    +--- Project ':addOns:importurls' - Adds an option to import a file of URLs. The file must be plain text with one URL per line.
|    +--- Project ':addOns:invoke' - Invoke external applications passing context related information such as URLs and parameters
|    +--- Project ':addOns:jruby' - Allows Ruby to be used for ZAP scripting - templates included
|    +--- Project ':addOns:jsonview' - Adds a view that shows JSON messages nicely formatted
|    +--- Project ':addOns:jxbrowsers' - Common configuration of the JxBrowser add-ons.
|    |    +--- Project ':addOns:jxbrowsers:jxbrowser' - An embedded browser based on Chromium, you must also install the relevant platform specific add-on
|    |    +--- Project ':addOns:jxbrowsers:jxbrowserlinux64' - An embedded browser based on Chromium, Linux 64 specific
|    |    +--- Project ':addOns:jxbrowsers:jxbrowsermacos' - An embedded browser based on Chromium, Mac OS specific
|    |    +--- Project ':addOns:jxbrowsers:jxbrowserwindows' - An embedded browser based on Chromium, Windows specific
|    |    \--- Project ':addOns:jxbrowsers:jxbrowserwindows64' - An embedded browser based on Chromium, Windows 64bits specific
|    +--- Project ':addOns:jython' - Allows Python to be used for ZAP scripting - templates included
|    +--- Project ':addOns:onlineMenu' - ZAP Online menu items
|    +--- Project ':addOns:openapi' - Imports and spiders Open API definitions.
|    +--- Project ':addOns:plugnhack' - Supports the Mozilla Plug-n-Hack standard: https://developer.mozilla.org/en-US/docs/Plug-n-Hack.
|    +--- Project ':addOns:portscan' - Allows to port scan a target server
|    +--- Project ':addOns:pscanrules' - The release quality Passive Scanner rules
|    +--- Project ':addOns:pscanrulesAlpha' - The alpha quality Passive Scanner rules
|    +--- Project ':addOns:pscanrulesBeta' - The beta quality Passive Scanner rules
|    +--- Project ':addOns:quickstart' - Provides a tab which allows you to quickly test a target application
|    +--- Project ':addOns:replacer' - Easy way to replace strings in requests and responses.
|    +--- Project ':addOns:requester' - Request numbered panel.
|    +--- Project ':addOns:reveal' - Show hidden fields and enable disabled fields
|    +--- Project ':addOns:revisit' - Revisit a site at any time in the past using the session history
|    +--- Project ':addOns:saml' - Detect, Show, Edit, Fuzz SAML requests
|    +--- Project ':addOns:saverawmessage' - Allows to save content of HTTP messages as binary
|    +--- Project ':addOns:savexmlmessage' - Allows to save content of HTTP messages as XML
|    +--- Project ':addOns:scripts' - Supports all JSR 223 scripting languages
|    +--- Project ':addOns:selenium' - WebDriver provider and includes HtmlUnit browser
|    +--- Project ':addOns:sequence' - Gives the possibility of defining a sequence of requests to be scanned.
|    +--- Project ':addOns:simpleexample' - A simple extension example.
|    +--- Project ':addOns:soap' - Imports and scans WSDL files containing SOAP endpoints.
|    +--- Project ':addOns:spiderAjax' - Allows you to spider sites that make heavy use of JavaScript using Crawljax
|    +--- Project ':addOns:sqliplugin' - An advanced active injection bundle for SQLi (derived by SQLMap)
|    +--- Project ':addOns:sse' - Allows you to view Server-Sent Events (SSE) communication.
|    +--- Project ':addOns:svndigger' - SVN Digger files which can be used with ZAP forced browsing
|    +--- Project ':addOns:tips' - Display ZAP Tips and Tricks
|    +--- Project ':addOns:tlsdebug' - Provides a tab which allows to quickly debug a TLS/SSL connection
|    +--- Project ':addOns:todo' - Provides a tab which allows you to view the list of test cases
|    +--- Project ':addOns:tokengen' - Allows you to generate and analyze pseudo random tokens, such as those used for session handling or CSRF protection
|    +--- Project ':addOns:treetools' - Tools to add functionality to the tree view.
|    +--- Project ':addOns:viewstate' - ASP/JSF ViewState Decoder and Editor
|    +--- Project ':addOns:vulncheck' - list vulnerabilities from known databases
|    +--- Project ':addOns:wappalyzer' - Technology detection using Wappalyzer: wappalyzer.com
|    +--- Project ':addOns:wavsepRpt' - Wavsep report generator.
|    +--- Project ':addOns:webdrivers' - Common configuration of the WebDriver add-ons.
|    |    +--- Project ':addOns:webdrivers:webdriverlinux' - Linux WebDrivers for Firefox and Chrome.
|    |    +--- Project ':addOns:webdrivers:webdrivermacos' - MacOS WebDrivers for Firefox and Chrome.
|    |    \--- Project ':addOns:webdrivers:webdriverwindows' - Windows WebDrivers for Firefox and Chrome.
|    +--- Project ':addOns:websocket' - Allows you to inspect WebSocket communication.
|    \--- Project ':addOns:zest' - A graphical security scripting language, ZAPs macro language on steroids
\--- Project ':testutils' - Common test utilities for the add-ons.
```

### New Add-On

The following steps are required to add a new add-on to the project:
1. Add the ID of the add-on to `addOns` list in `settings.gradle.kts`;
1. Create the add-on directory under `addOns` directory and add its build file.

## Open Pull Requests

The pull requests will be migrated to the new structure (and target master) once the branches are merged, the author of the pull request does not need to do anything other than fetch the remote changes when the full migration is done. (Feel free to force push any local changes that you might have, let us know and the pull request will be migrated again.)

## Quick Migration Guide

This section provides some information on how to use the new build from command line and in IDEs.

The following table shows the corresponding Gradle tasks for the (old) Ant targets:

| Ant Targets       | Gradle Tasks                |
|:------------------|:----------------------------|
| `build-all`       | `build`                     |
| `test`            | `test`                      |
| `deploy-*`        | `copyZapAddOn`              |
| `generate-wiki-*` | `copyWiki-help`             |
| `generate-apis`   | `generateZapApiClientFiles` |
| `deploy-release`  | `copyMainAddOns`            |
| `deploy-weely`    | `copyWeeklyAddOns`          |

The new build provides more useful tasks, for example, with `installZapAddOn` it's possible to install an add-on into running ZAP (requires newer weekly versions, started with `-dev` flag and listen on 8080 by default).

### Command Line

Instead of using `ant` use `gradlew` (or `gradle`, if compatible with 5.x) with the mentioned tasks.
 
If running the command from the top level directory the full path to the project must be provided:
```
gradle :addOns:accessControl:copyZapAddOn
```
if from an add-on (e.g. `accessControl`) directory just the task name:
```
gradle copyZapAddOn
```

Refer to [Command-Line Interface docs](https://docs.gradle.org/current/userguide/command_line_interface.html) for more details about command line usage (e.g. `tasks`, Task name abbreviation).

### IntelliJ IDEA

The zap-extensions repo should be [imported as a Gradle project](https://www.jetbrains.com/help/idea/gradle.html#gradle_import), once imported the Gradle tasks can be executed from the [Gradle Tool Window](https://www.jetbrains.com/help/idea/jetgradle-tool-window.html).

### Eclipse

The zap-extensions repo should be [imported as a Gradle project](https://www.vogella.com/tutorials/EclipseGradle/article.html#import-an-existing-gradle-project), once imported the Gradle tasks can be executed from the [Gradle Tasks view](https://www.vogella.com/tutorials/EclipseGradle/article.html#using-the-gradle-tasks-view).
It's recommended to select a Working Set when importing to keep the projects better organised.

To avoid project (name) collision with 3rd-party projects it's recommended to use a Workspace just for ZAP projects.

## Comments/Questions

Use the following thread for comments and questions related to the merge and build changes:
https://groups.google.com/d/topic/zaproxy-develop/GqLZz9ex0F4/discussion

**Comment by kingthorin** [comment]
The open issues task can be marked completed?

**Comment by thc202** [comment]
I believe there are still some issues open that refer to old locations.

**Comment by kingthorin** [comment]
Ok, no worries.

**Comment by thc202** [comment]
Updated some more open issues (mostly in comments) to link to new locations.

**Comment by thc202** [comment]
Closing, all seems to be done.

Feel free to leave a comment (or raise a new issue) if you spot something missing/wrong.
