### ISSUE TITLE
Passive Scanning WebSockets

### ISSUE THREAD

**Issue by ManosMagnus** [zaproxy/zaproxy#5346]
**Expectations**

An infrastructure which allows passively examination of WebSocket messages. The infrastructure should support plugin additions, scripts and API, all the above should be able to raise the appropriate alerts. 

**Current State**

- [ ]  [PR#1718](https://github.com/zaproxy/zap-extensions/pull/1718) Script Mechanism
Contains:
     * Basic infrastructure - Iterates over the stored websocket messages and, in turn, apply the passive script plugin
     * Templates for Python and JavaScript 
     * Scripts are able to raise alerts. However, because of related issue 1 the alerts point on handshake message. 
 

**TODOs**
- [ ] Support Plugin Addition
   - [ ] Usable UI
- [ ] API

**Possible Scans**
- [ ] Base64 Disclosure: Scan responses for Base64 Hashes (either plugin or script)

**Related Issues**

1.  [Enhancement: Add support for raising alerts for other than HTTP/1.x interactions](https://github.com/zaproxy/zaproxy/issues/2464)

Note any additional expectations and possible scans which will be great to be supported

**Comment by ManosMagnus** [comment]
Following exceptions are triggered using Passive Scan Script with ZAP HUD. Maybe is related to the fact that HUD uses websocket without establish the connection via handshake  
```
786919 [Thread-12] WARN org.zaproxy.zap.extension.websocket.pscan.WebSocketPassiveScanThread  - Could not get messages from database
org.parosproxy.paros.db.DatabaseException: java.sql.SQLException: Message not found!
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.getMessage(TableWebSocket.java:361)
	at org.zaproxy.zap.extension.websocket.pscan.WebSocketPassiveScanThread.run(WebSocketPassiveScanThread.java:144)
Caused by: java.sql.SQLException: Message not found!
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.getMessage(TableWebSocket.java:357)
	... 1 more
786927 [Thread-12] INFO org.zaproxy.zap.extension.websocket.alerts.WebSocketAlertWrapper  - Couldn't get the Handshake Http Message for this specific channel
java.lang.NullPointerException
	at org.zaproxy.zap.extension.websocket.alerts.WebSocketAlertWrapper.setDetail(WebSocketAlertWrapper.java:71)
	at org.zaproxy.zap.extension.websocket.pscan.scripts.ScriptsWebSocketPassiveScanner$AlertRaiser.raiseAlert(ScriptsWebSocketPassiveScanner.java:109)
	at jdk.nashorn.internal.scripts.Script$Recompilation$2715$1563AA$\^eval\_.scan(<eval>:66)
	at org.zaproxy.zap.extension.websocket.pscan.scripts.WebSocketPassiveScript$$NashornJavaAdapter.scan(Unknown Source)
	at org.zaproxy.zap.extension.websocket.pscan.scripts.ScriptsWebSocketPassiveScanner.scanMessage(ScriptsWebSocketPassiveScanner.java:73)
	at org.zaproxy.zap.extension.websocket.pscan.WebSocketPassiveScannerDecorator.scanMessage(WebSocketPassiveScannerDecorator.java:37)
	at org.zaproxy.zap.extension.websocket.pscan.WebSocketPassiveScannerPlugin.scanMessage(WebSocketPassiveScannerPlugin.java:25)
	at org.zaproxy.zap.extension.websocket.pscan.WebSocketPassiveScanThread.run(WebSocketPassiveScanThread.java:149)
786928 [Thread-12] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - Attempting to raise an alert without URI and/or HTTP message, Plugin ID: 110000 Alert Name:name of the alert
	java.lang.Thread.getStackTrace(Thread.java:1559)
	org.zaproxy.zap.extension.alert.ExtensionAlert.isInvalid(ExtensionAlert.java:237)
	org.zaproxy.zap.extension.alert.ExtensionAlert.alertFound(ExtensionAlert.java:174)
	org.zaproxy.zap.extension.websocket.alerts.AlertManager.alertFound(AlertManager.java:35)
	org.zaproxy.zap.extension.websocket.pscan.WebSocketPassiveScanThread.raiseAlert(WebSocketPassiveScanThread.java:166)
	org.zaproxy.zap.extension.websocket.pscan.scripts.ScriptsWebSocketPassiveScanner$AlertRaiser.raiseAlert(ScriptsWebSocketPassiveScanner.java:111)
	jdk.nashorn.internal.scripts.Script$Recompilation$2715$1563AA$\^eval\_.scan(<eval>:66)
	org.zaproxy.zap.extension.websocket.pscan.scripts.WebSocketPassiveScript$$NashornJavaAdapter.scan(Unknown Source)
	org.zaproxy.zap.extension.websocket.pscan.scripts.ScriptsWebSocketPassiveScanner.scanMessage(ScriptsWebSocketPassiveScanner.java:73)
	org.zaproxy.zap.extension.websocket.pscan.WebSocketPassiveScannerDecorator.scanMessage(WebSocketPassiveScannerDecorator.java:37)
	org.zaproxy.zap.extension.websocket.pscan.WebSocketPassiveScannerPlugin.scanMessage(WebSocketPassiveScannerPlugin.java:25)
	org.zaproxy.zap.extension.websocket.pscan.WebSocketPassiveScanThread.run(WebSocketPassiveScanThread.java:149)
```

**Comment by ManosMagnus** [comment]
Application Error disclosure script in javascript was added
