### ISSUE TITLE
[Tracker] WebSocket TreeMap & Payload Analyzers

### ISSUE THREAD

**Issue by ManosMagnus** [zaproxy/zaproxy#5539]
# WebSocket TreeMap & Analyzers
<a id="org01339c2"></a>

## Expectations

The expectations here is to display WebSocket Message in a Tree Structure
same as Https ones. More specifically, the messages should be sorted under
their hosts and reveal their Payload Structure. Payload Structure is that
"object" that makes payload useful to inject your values. For example, a
comma separated Payload Structure should give you the ability to inject
values between commas. To depict that, the expectations is presented to the
following figure:

    
    +-------------+
    |     Root    +---------------------> Contains all WebSocket Hosts
    +-+-----------+
      |     +---------------+
      +-----+  JSON Host    +-----------> Should be able to identify the
      |     +---------------+             the Payload Structure of the messages.
      |      | +-----------------+
      |      +-+ {"username":    |
      |        |    {@id} }      |----------> Should be able to inject a value
      |        +-----------------+            at the {@id} position.
      |     +---------------+
      +-----+  CSV Host     |
            +---------------+
             | +-----------------+
             +-+ {@id1},{@id2}   +---------> Should be able to choose among
             | |    {@id3},      |           the different Payload Analyzers
             | +-----------------+
             | +-----------------+
             --+ "simple msg"    +---------> Messages without a specific
               +-----------------+           Payload Structure should be
                      |                      displayed just with their Payload.
                      |
                      |
                      v
           Should be able to write a plugin/script to analyze it.

<a id="orgd8021fd"></a>

### Assumptions (currently)

-   We only care about WebSocket Messages which have String payload

-   All messages should be contained in the Tree Structure even if they
    couldn't be analyzed.

-   A node in Tree Structure should be able to change content if need be. For
    example, we should update a node if a new message has been transmitted or
    a Payload Analyzer have been changed.

-   Since the payload structure could be the same in more than one messages,
    then the nodes should store only the last one (or the values only).

-   We have to make a mechanism to run plugins and scripts.

-   We should be able to get WebSocket Message(s) or Payload Structure(s) from
    every possible node of the Tree Structure.

-   Names of the nodes should be defined by the Payload Structure. 
    
    Tech Spec [here](https://docs.google.com/document/d/1TllW7AkTUZHc5Au7fQDYQLMTfOiYwm-luhJNiSn1xvo/edit#) gives more details about assumption and some implementation
    issues.

<a id="orgdb22f80"></a>

## Current State

<a id="org1d352c3"></a>

### Pending
- [ ] WebSocket Tree Map - Functionality ([PR#2135](https://github.com/zaproxy/zap-extensions/pull/2135))
    - [ ] <span class="underline">Reviewing</span> - Should be approved by ZAP team.
- [ ] Payload Analyzer   - Functionality ([PR#2147](https://github.com/zaproxy/zap-extensions/pull/2147))
   - [ ] Waiting [PR#2135](https://github.com/zaproxy/zap-extensions/pull/2135) to be approved
- [ ] JSON Analyzer      - Functionality ([PR#2147](https://github.com/zaproxy/zap-extensions/pull/2147))
   - [ ] Waiting [PR#2135](https://github.com/zaproxy/zap-extensions/pull/2135) to be approved

### TODOs (Currently)
- [ ] Create the appropriate infrastructure to support plugins and scripts 
- [ ] Implement UI

**Comment by kingthorin** [comment]
For inspiration/ideas: https://hacks.mozilla.org/2019/10/firefoxs-new-websocket-inspector/
> The inspector currently supports the following WS protocols – and we have more planned:
> Plain JSON
> Socket.IO
> SockJS
