### ISSUE TITLE
Improve dark mode

### ISSUE THREAD

**Issue by epicodertime** [zaproxy/zaproxy#5542]
It would be nice for appearance for the program 

Updating to make this into a tracker:

- [x] Add FlatLaf to core
- [x] Fix splash screen (Make the tips panel slightly smaller and move it down slightly so that the bottom panel only shows 5 lines [at default font settings/lang]?) [This screenshot is shrunk to 75% for ticket inclusion]

<details>
<summary>Screenshot <sub>(Click the triangle/control to the left to expand)</sub></summary>

![image](https://user-images.githubusercontent.com/7570458/75348496-f3516280-5870-11ea-846a-5f921e0cc89d.png)

</details>

- [x] Fix Quick start panel
- [x] Fix Request / response / break panels
- [x] Fix manual request dialog
- [x] Fix WebSocket message editor
- [x] Fix script console
- [x] Fix About screen
- [x] Fix Java help pages
- [x] Fix Encode/decode/hash (black text)
- [x] Fix Options / Check For Updates (black text)
- [x] Fix Options headings:

<details>
<summary>Screenshot <sub>(Click the triangle/control to the left to expand)</sub></summary>

![image](https://user-images.githubusercontent.com/7570458/75347787-8be6e300-586f-11ea-9717-096fe4e8728b.png)

</details>

- Highlight contrast concerns:
  - [x] https://github.com/zaproxy/zaproxy/issues/5542#issuecomment-591419439 > Options Panel(s) Search Highlighting (Reference: https://github.com/zaproxy/zaproxy/pull/4141/) (Done in: https://github.com/zaproxy/zaproxy/pull/6328)
  - [x] Find Dialog Highlighting (CTRL + F) (Done in: https://github.com/zaproxy/zaproxy/pull/6328)
  - [x] https://github.com/zaproxy/zaproxy/issues/5542#issuecomment-643019236 > Highlighting in request/response panels, as a result of Alert highlighting or Search tab highlighting (it's more 'white' than the normal click & drag highlight) (Done in: https://github.com/zaproxy/zaproxy/pull/6329)
- [x] Active Scan progress dialog: https://github.com/zaproxy/zaproxy/issues/5542#issuecomment-606977117 (Done in: https://github.com/zaproxy/zaproxy/pull/6262)

Add anything else you find above...

**Comment by thc202** [comment]
ZAP uses Swing for the UI, the following might be a good start to know how it works: https://docs.oracle.com/javase/tutorial/uiswing/lookandfeel/index.html specially the "Changing the Color Theme" (although it might worth searching for a L&F that provides a dark mode already).

In ZAP a good place to tweak the theme (or try custom/other L&Fs) would be in `GuiBootstrap#setupLookAndFeel`.

**Comment by psiinon** [comment]
@epicodertime the ZAP core code containing the main UI is under https://github.com/zaproxy/zaproxy/tree/develop/zap/src/main/java/org
Add-on can also add UI elements, but hopefully a L&F change as suggested in https://github.com/zaproxy/zaproxy/issues/5542#issuecomment-525922602 will do the trick

**Comment by DevCharly** [comment]
If you guys are still looking for a dark Swing L&F,
you could try FlatLaf (https://github.com/JFormDesigner/FlatLaf).
It comes with dark and light themes and scales on HiDPI screens.

**Comment by thc202** [comment]
What's the history of FlatLaf?

ZAP with `FlatDarkLaf`:
![ZAP with FlatDarkLaf](https://user-images.githubusercontent.com/4639210/75080171-214a4600-5503-11ea-870d-607012985a83.png)

**Comment by DevCharly** [comment]
> What's the history of FlatLaf?

I've started FlatLaf project about 6 months ago to implement a good looking cross platform dark and light look and feel that scales on HiDPI screens. The idea was to replace all platform specific L&Fs usually used in an application with a single L&F. This saves a lot of time for testing and fixing the UI on multiple platforms. The FlatLaf look is heavily inspired by Darcula and IntelliJ themes from IntelliJ IDEA. There are already a lot of projects using FlatLaf. E.g. NetBeans 11.3, which will be released soon.

**Comment by psiinon** [comment]
Looks good, although we might need to tweak the Quick Start tab to look better. @thc202 did you notice any other screens that might need adjusting?

**Comment by thc202** [comment]
The start up dialogue and some text areas (ones using `RSyntaxTextArea`).

**Comment by psiinon** [comment]
@DevCharly you on twitter? Want to tweet about this and will include your handle :)

**Comment by kingthorin** [comment]
Note some of the misses might be due to:
* [Internal Frames do not have decorations corresponding to FlatLaf](https://github.com/JFormDesigner/FlatLaf/issues/39)
* [Look-and-feel-decorated JFrames do not render properly](https://github.com/JFormDesigner/FlatLaf/issues/47)

**Comment by psiinon** [comment]
https://twitter.com/psiinon/status/1232299460019052546 (used https://twitter.com/JFormDesigner)

**Comment by DevCharly** [comment]
> @DevCharly you on twitter? Want to tweet about this and will include your handle :)

Yes, here: https://twitter.com/JFormDesigner
Thx

**Comment by DevCharly** [comment]
@kingthorin

The first issue https://github.com/JFormDesigner/FlatLaf/issues/39 is already implemented in FlatLaf 0.27. I've closed it now.

The second issue https://github.com/JFormDesigner/FlatLaf/issues/47 is not relevant for zaproxy because it does not use `JRootPane.setWindowDecorationStyle(int)`.

**Comment by psiinon** [comment]
@DevCharly any immediate thoughts on why some of the ZAP screens might not be picking up the dark mode (as per the tweet)? Dont expect you to debug it, but pointers to common problems might save us some time so would be much appreciated :)

**Comment by psiinon** [comment]
As per https://github.com/zaproxy/zaproxy/issues/5542#issuecomment-590253633 looks like getting FlatLaf working with RSyntaxTextArea would solve a load of the problem screens...

**Comment by DevCharly** [comment]
@psiinon usually hard-coded colors. Searching for [Color.WHITE](https://github.com/zaproxy/zaproxy/search?q=%22color.white%22&unscoped_q=%22color.white%22) and [new Color](https://github.com/zaproxy/zaproxy/search?q=%22new+color%22&unscoped_q=%22new+color%22) shows some of them.

`Color.WHITE` could be replaced with `UIManager.getColor("TextField.background")` because `TextField.background` is white on all light L&Fs.

It is always best to get colors from `UIManager` because they match the L&F.

**Comment by kingthorin** [comment]
@DevCharly thanks for clarifying those two items!

**Comment by DevCharly** [comment]
If there are many custom colors used in zaproxy, it might be useful to put them into a FlatLaf properties file. Then it is easy to access them. E.g.

~~~java
Color color = UIManager.getColor("my.custom.color.stored.in.properties.file");
if( color == null )
   color = hardCodedColorForOtherLafs;
// use color
~~~

All you need is
- a properties file named `FlatDarkLaf.properties` (e.g. in `src/main/resources/org/zaproxy/zap/resources`)
- an empty class extending `com.formdev.flatlaf.FlatDefaultsAddon` (in the same package as `FlatDarkLaf.properties`
- a service provider-configuration file named `META-INF/services/com.formdev.flatlaf.FlatDefaultsAddon`

Here are examples from NetBeans: [FlatDarkLaf.properties](https://github.com/apache/netbeans/blob/master/platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatDarkLaf.properties), [NbFlatDefaultsAddon.java](https://github.com/apache/netbeans/blob/master/platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/NbFlatDefaultsAddon.java) and [META-INF/services/com.formdev.flatlaf.FlatDefaultsAddon](https://github.com/apache/netbeans/blob/master/platform/o.n.swing.laf.flatlaf/src/META-INF/services/com.formdev.flatlaf.FlatDefaultsAddon)

**Comment by DevCharly** [comment]
RSyntaxTextArea supports themes (see https://github.com/bobbylight/RSyntaxTextArea/wiki/Example:-Setting-the-theme) and there is a dark one here: https://github.com/bobbylight/RSyntaxTextArea/blob/master/RSyntaxTextArea/src/main/resources/org/fife/ui/rsyntaxtextarea/themes/dark.xml

**Comment by DevCharly** [comment]
RSyntaxTextArea supports themes (see https://github.com/bobbylight/RSyntaxTextArea/wiki/Example:-Setting-the-theme) and there is a dark one here: https://github.com/bobbylight/RSyntaxTextArea/blob/master/RSyntaxTextArea/src/main/resources/org/fife/ui/rsyntaxtextarea/themes/dark.xml

**Comment by kingthorin** [comment]
The Options search functionality might need a different highlight colour for different L&Fs. The grey text is hard to read on a yellow background:
![image](https://user-images.githubusercontent.com/7570458/75347996-fac43c00-586f-11ea-8b88-203d602c1b7b.png)

**Comment by psiinon** [comment]
Set the RSyntaxTextArea theme to their dark mode in the HttpPanelSyntaxHighlightTextArea constructor for a test:
![Screenshot from 2020-02-27 10-37-17](https://user-images.githubusercontent.com/1081115/75437013-7942db80-594d-11ea-9805-7122b484a76b.png)

**Comment by psiinon** [comment]
FYI the above hack works for the request / response / break panels and manual request dialog.

**Comment by DiogoMRSilva** [comment]
Hello, When you chose one of the flat themes you can't change the fonts used neither their size:
![Screenshot from 2020-03-06 16-14-44](https://user-images.githubusercontent.com/6045401/76102918-a2f0a800-5fc8-11ea-867b-3d34d23d00a4.png)
If you change from an old theme and at the same time increase the font size:
![Screenshot from 2020-03-06 16-41-26](https://user-images.githubusercontent.com/6045401/76103316-65404f00-5fc9-11ea-9cf5-cea89213f2bb.png)
Even when the font size is set ZAP is not using it.

I love this new themes, nice work :)

**Comment by psiinon** [comment]
Thats weird :/ @DevCharly do your themes support changing the font size?

**Comment by thc202** [comment]
It might be our check that's not correct: https://github.com/zaproxy/zaproxy/blob/a61253d6603f0485d534a598e96d15287234ced4/zap/src/main/java/org/zaproxy/zap/utils/FontUtils.java#L92-L94

**Comment by kingthorin** [comment]
@DevCharly any idea why some Unicode characters don't render properly?

![image](https://user-images.githubusercontent.com/7570458/76127054-b0109580-5fce-11ea-9be0-d922d121715e.png)

[Full Block `\u2588`](https://www.fileformat.info/info/unicode/char/2588/index.htm)
[Multiplication X `\u2715`](https://www.fileformat.info/info/unicode/char/2715/index.htm)

Nimbus:
![image](https://user-images.githubusercontent.com/7570458/76127538-e7337680-5fcf-11ea-9fe6-e81ceb3e8999.png)

**Comment by thc202** [comment]
That's because of the font, in Linux it renders fine (though without the colour): 
![neon-flatlaf-dark](https://user-images.githubusercontent.com/4639210/76131646-3ba61880-6007-11ea-9b38-0fa4bd399328.png)

**Comment by kingthorin** [comment]
Huh okay. 

I decided to change how the drop down works, still need to sort out the X button though.

**Comment by w3b-mani4k** [comment]
Hi!
when is the release with a dark theme?

**Comment by kingthorin** [comment]
The initial release was in a weekly a few weeks ago. Announcement here: https://www.zaproxy.org/blog/2020-03-04-dark-mode-in-the-weekly-release/

If you mean for a stable release it’ll probably be after the summer. Whenever we ship 2.10.

**Comment by thc202** [comment]
Tweaked the title, this issue is now tracking improvements.

**Comment by kingthorin** [comment]
Looks like the Active Scan Progress dialog could use some tweaks for dark mode:
![image](https://user-images.githubusercontent.com/7570458/78090706-de4c7f80-7398-11ea-90dc-e2763e8292df.png)

**Comment by DevCharly** [comment]
>  @DevCharly do your themes support changing the font size?

Yes, since FlatLaf 0.29.

Works the same way as in Nimbus L&F.
No changes necessary in zaproxy.

**Comment by DevCharly** [comment]
> 
> 
> @DevCharly any idea why some Unicode characters don't render properly?
> 
> ![image](https://user-images.githubusercontent.com/7570458/76127054-b0109580-5fce-11ea-9be0-d922d121715e.png)
> 
> [Full Block `\u2588`](https://www.fileformat.info/info/unicode/char/2588/index.htm)
> [Multiplication X `\u2715`](https://www.fileformat.info/info/unicode/char/2715/index.htm)
> 
> Nimbus:
> ![image](https://user-images.githubusercontent.com/7570458/76127538-e7337680-5fcf-11ea-9fe6-e81ceb3e8999.png)

@kingthorin this is now fixed in FlatLaf 0.30, which now creates composite fonts that are able to render all Unicode characters.

**Comment by kingthorin** [comment]
@DevCharly thanks!

**Comment by DevCharly** [comment]
BTW just remembered that it is possible to set custom font in ZAP Options dialog. This may cause the same problem with Unicode characters, but it is easy to fix.

To create a composite font that renders Unicode use:
~~~java
Font font = new javax.swing.text.StyleContext().getFont( family, style, size );
~~~
instead of
~~~java
Font font = new Font( family, style, size );
~~~

**Comment by kingthorin** [comment]
@DevCharly thanks again!

**Comment by kingthorin** [comment]
I think we're going to need to look into optimal highlight color (contrast) calculations or something:
![image](https://user-images.githubusercontent.com/7570458/84456013-e80e2100-ac2c-11ea-999a-7e2ede756880.png)
![image](https://user-images.githubusercontent.com/7570458/84456039-fbb98780-ac2c-11ea-8e0d-37b38dda1d98.png)
![image](https://user-images.githubusercontent.com/7570458/84456058-0d029400-ac2d-11ea-9e40-fd1bb7cc81b7.png)

**Comment by thc202** [comment]
What's highlighting that? Search tab?

**Comment by kingthorin** [comment]
First one is alert, 2nd/3rd are search.

**Comment by psiinon** [comment]
Think this is now complete. If anyone finds any new issues them please raise a new issue.

**Comment by kingthorin** [comment]
I'll open separate issues for:
- Highlight contrast concerns:
  - https://github.com/zaproxy/zaproxy/issues/5542#issuecomment-591419439
  - https://github.com/zaproxy/zaproxy/issues/5542#issuecomment-643019236
- Active Scan progress dialog: https://github.com/zaproxy/zaproxy/issues/5542#issuecomment-606977117

(Links might be to hidden comments. )

**Comment by psiinon** [comment]
If they had been in the tracker then I would have known not to close it ;)
OK reopenning it if you like?

**Comment by thc202** [comment]
Reopening to keep everything tracked in the same issue.

**Comment by kingthorin** [comment]
Thanks!

Sorry I wasn't consistent in using the todo bullets or more pushy when commenting to get consensus that they were actually issues.

**Comment by psiinon** [comment]
Have added those checkboxes :)

**Comment by kingthorin** [comment]
It seems like some of the highlight contrast concerns may have been addressed by our recent Flatlaf dependency upgrade, the following are Scripts Console and request/response:
![image](https://user-images.githubusercontent.com/7570458/97081139-68c32d80-15ce-11eb-95ce-7d25c5b73ae2.png)
![image](https://user-images.githubusercontent.com/7570458/97081163-7d9fc100-15ce-11eb-9db2-ff5bd952e9a4.png)

**Comment by thc202** [comment]
The comment referenced is about our highlighting (search/alert) not the normal text highlighting(?).

**Comment by kingthorin** [comment]
I'll double check that behavior as well, get back to you shortly.

**Comment by kingthorin** [comment]
Okay sadly you're right. Normal (click and drag) highlighting is fine, search in pane (ctrl + F) is fine. But search panel search highlight and alert highlight uses a more white highlight that's problematic 😞

**Comment by psiinon** [comment]
Are the 2 remaining items now fixed? The Find dialog should have been fixed by my last PR...

**Comment by kingthorin** [comment]
Yup, all done.
