### ISSUE TITLE
Release 2.9.0

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#5809]
- [x] Create/update admin config files
  - [x] ZapVersions
  - [x] News
- [x] Create branch
- [x] Build release
- [x] Test installers
  - [x] Windows 64
  - [x] Windows 32
  - [x] Linux
  - [x] Mac
- [x] Publish release
- [x] Docs
  - [x] Update User Guide
  - [x] Update version in questionnaire
  - [x] Update version on https://bugcrowd.com/owaspzap
- [x] Update Downloads page
- [x] Announce
  - [x] Twitter
  - [x] ZAP Groups
  - [x] OWASP Slack
- [x] Inform package maintainers
  - [x] Kali
  - [x] Linux distros (Cabelo)
  - [x] Homebrew
  - [x] Flathub
- [x] Update Docker images
  - [x] Stable
  - [x] Bare
- [x] Update Snapcraft
- [x] Release to Maven Central
- [x] Release APIs
  - [x] Java
  - [x] Python

**Comment by psiinon** [comment]
Update with more tasks as you think of them. We should save this as a standard template for future releases...

**Comment by DavidCarrington** [comment]
Docker image owasp/zap2docker-stable is giving these errors as of a few hours ago - is this related?

> RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Either switch to Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.

**Comment by psiinon** [comment]
@DavidCarrington It could be - could you raise a new issue giving full details pf the error, and stack traces etc. Note that the stable release is tagged so if this is causing you problems then you can explicitly use the 2.8.0 tag to get around this problem.

**Comment by thc202** [comment]
That's because of https://github.com/zaproxy/zaproxy/blob/develop/docker/CHANGELOG.md#2019-10-01
