### ISSUE TITLE
Encoder Add-on Tracker

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#5996]
- [x] Migrate core components. (Done in: https://github.com/zaproxy/zap-extensions/pull/2412 and https://github.com/zaproxy/zap-extensions/pull/2409)
- [x] Deprecate core components. (Done in: https://github.com/zaproxy/zaproxy/pull/6011)
- [x] Remove core help content. (Done in https://github.com/zaproxy/zap-core-help/pull/313/)
- [x] Hide/un-use core components.
- [x] Remove previously deprecated core code. (After 2.10.0) (Done in https://github.com/zaproxy/zaproxy/pull/6436.)
  - [x] And no longer needed message keys (Messages.properties). (done in: https://github.com/zaproxy/zaproxy/pull/6070)
- [x] Migrate help content. (Done in: https://github.com/zaproxy/zap-extensions/pull/2408)
- [x] Implement other templates/examples? (Maybe ROT13? or ROTn. Done in: https://github.com/zaproxy/zap-extensions/pull/2426)
- [x] In the new add-on remove "Advanced", after 2.10.0 and add-on targeting 2.10.0. (Done in: https://github.com/zaproxy/zap-extensions/pull/2614)

**Comment by kingthorin** [comment]
Are we good with proceeding on the core removal? (Help and Menu Item ... the code can be left for a bit and just unused on the off chance that there's some third party dependency.)

**Comment by kingthorin** [comment]
Re-opened as I realized I never went back and updated templates for other scripting engines.

**Comment by kingthorin** [comment]
Assuming my syntax was correct for these scripts there seems to be a visibility/classloader issue with Kotlin/JRuby.

Went to do the Kotlin template:
```kotlin
import org.zaproxy.addon.encoder.processors.EncodeDecodeResult
import org.zaproxy.addon.encoder.processors.script.EncodeDecodeScriptHelper

/**
 * Process the input value and return the encoded/decoded/hashed etc. value
 *
 * Use helper.newError("Error Description") to provide an error description
 * inside the result view.
 *
 * @param {EncodeDecodeScriptHelper} helper - A helper object with various utility methods.
 *     For more details see https://github.com/zaproxy/zap-extensions/tree/main/addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/script/EncodeDecodeScriptHelper.java
 * @param {String} value - The input value
 * @returns {EncodeDecodeResult} - The value that was encoded/decoded/hashed etc. easiest via helper.newResult(result).
 */
fun process(helper: EncodeDecodeScriptHelper, value: String): EncodeDecodeResult {
	return helper.newResult(value);
}
```

<details>
<summary>Stacktrace (Click the triangle/control to expand)</summary>

```
org.zaproxy.addon.encoder.processors.script.EncodeDecodeScript referenced from a method is not visible from class loader
java.lang.IllegalArgumentException: org.zaproxy.addon.encoder.processors.script.EncodeDecodeScript referenced from a method is not visible from class loader
	at java.lang.reflect.Proxy$ProxyBuilder.ensureVisible(Proxy.java:858) ~[?:?]
	at java.lang.reflect.Proxy$ProxyBuilder.validateProxyInterfaces(Proxy.java:681) ~[?:?]
	at java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:627) ~[?:?]
	at java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:635) ~[?:?]
	at java.lang.reflect.Proxy.lambda$getProxyConstructor$0(Proxy.java:415) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205) ~[?:?]
	at java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:413) ~[?:?]
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1006) ~[?:?]
	at kotlin.script.experimental.jvmhost.jsr223.KotlinJsr223InvocableScriptEngine$DefaultImpls.proxyInterface(KotlinJsr223InvocableScriptEngine.kt:80) ~[?:?]
	at kotlin.script.experimental.jvmhost.jsr223.KotlinJsr223InvocableScriptEngine$DefaultImpls.getInterface(KotlinJsr223InvocableScriptEngine.kt:66) ~[?:?]
	at kotlin.script.experimental.jvmhost.jsr223.KotlinJsr223ScriptEngineImpl.getInterface(KotlinJsr223ScriptEngineImpl.kt:24) ~[?:?]
	at org.zaproxy.zap.extension.script.ExtensionScript.getInterface(ExtensionScript.java:2003) [main/:?]
	at org.zaproxy.addon.encoder.processors.script.ScriptBasedEncodeDecodeProcessor.evaluateScript(ScriptBasedEncodeDecodeProcessor.java:109) ~[encoder-release-1.2.0.zap:?]
	at org.zaproxy.addon.encoder.processors.script.ScriptBasedEncodeDecodeProcessor.process(ScriptBasedEncodeDecodeProcessor.java:75) [encoder-release-1.2.0.zap:?]
	at org.zaproxy.addon.encoder.processors.EncodeDecodeProcessors.process(EncodeDecodeProcessors.java:168) [encoder-release-1.2.0.zap:?]
	at org.zaproxy.addon.encoder.EncodeDecodeDialog.updateEncodeDecodeField(EncodeDecodeDialog.java:636) [encoder-release-1.2.0.zap:?]
	at org.zaproxy.addon.encoder.EncodeDecodeDialog.updateEncodeDecodeFields(EncodeDecodeDialog.java:626) [encoder-release-1.2.0.zap:?]
	at org.zaproxy.addon.encoder.EncodeDecodeDialog$3.insertUpdate(EncodeDecodeDialog.java:569) [encoder-release-1.2.0.zap:?]
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:203) [?:?]
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:757) [?:?]
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:716) [?:?]
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:131) [?:?]
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:675) [?:?]
	at javax.swing.text.JTextComponent.replaceSelection(JTextComponent.java:1339) [?:?]
	at javax.swing.text.DefaultEditorKit$DefaultKeyTypedAction.actionPerformed(DefaultEditorKit.java:884) [?:?]
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810) [?:?]
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2900) [?:?]
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2948) [?:?]
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2862) [?:?]
	at java.awt.Component.processEvent(Component.java:6412) [?:?]
	at java.awt.Container.processEvent(Container.java:2263) [?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950) [?:?]
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:870) [?:?]
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139) [?:?]
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009) [?:?]
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835) [?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:4892) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) [?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
```

</details>

Similar for Ruby:

```rb
def process(helper, value){
	return helper.newResult(value + "fred");
end
```

<details>
<summary>Stacktrace (Click the triangle/control to expand)</summary>

```
java.lang.NoClassDefFoundError: Could not initialize class org.jruby.RubyInstanceConfig
	at org.jruby.embed.internal.AbstractLocalContextProvider.<init>(AbstractLocalContextProvider.java:42) ~[?:?]
	at org.jruby.embed.internal.SingletonLocalContextProvider.<init>(SingletonLocalContextProvider.java:88) ~[?:?]
	at org.jruby.embed.ScriptingContainer.getProviderInstance(ScriptingContainer.java:246) ~[?:?]
	at org.jruby.embed.ScriptingContainer.<init>(ScriptingContainer.java:226) ~[?:?]
	at org.jruby.embed.jsr223.JRubyEngineFactory.getScriptEngine(JRubyEngineFactory.java:170) ~[?:?]
	at org.zaproxy.zap.extension.script.ScriptEngineWrapper.getEngine(ScriptEngineWrapper.java:63) ~[main/:?]
	at org.zaproxy.zap.extension.jruby.JrubyScriptWrapper.getInterface(JrubyScriptWrapper.java:42) ~[?:?]
	at org.zaproxy.zap.extension.script.ExtensionScript.getInterface(ExtensionScript.java:1987) ~[main/:?]
	at org.zaproxy.addon.encoder.processors.script.ScriptBasedEncodeDecodeProcessor.evaluateScript(ScriptBasedEncodeDecodeProcessor.java:109) ~[?:?]
	at org.zaproxy.addon.encoder.processors.script.ScriptBasedEncodeDecodeProcessor.process(ScriptBasedEncodeDecodeProcessor.java:75) ~[?:?]
	at org.zaproxy.addon.encoder.processors.EncodeDecodeProcessors.process(EncodeDecodeProcessors.java:168) ~[?:?]
	at org.zaproxy.addon.encoder.EncodeDecodeDialog.updateEncodeDecodeField(EncodeDecodeDialog.java:636) ~[?:?]
	at org.zaproxy.addon.encoder.EncodeDecodeDialog.updateEncodeDecodeFields(EncodeDecodeDialog.java:626) ~[?:?]
	at org.zaproxy.addon.encoder.EncodeDecodeDialog$3.insertUpdate(EncodeDecodeDialog.java:569) ~[?:?]
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:203) ~[?:?]
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:757) ~[?:?]
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:716) ~[?:?]
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:131) ~[?:?]
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:675) ~[?:?]
	at javax.swing.text.JTextComponent.replaceSelection(JTextComponent.java:1339) ~[?:?]
	at javax.swing.text.DefaultEditorKit$DefaultKeyTypedAction.actionPerformed(DefaultEditorKit.java:884) ~[?:?]
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810) ~[?:?]
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2900) ~[?:?]
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2948) ~[?:?]
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2862) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6412) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2263) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950) ~[?:?]
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:870) ~[?:?]
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139) ~[?:?]
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009) ~[?:?]
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:4892) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
```

</details>

**Comment by thc202** [comment]
The Kotlin case is a class loading issue. The JRuby is failing because that does not work with Java 11 (#3944), you need to check the first exception though.
