### ISSUE TITLE
Scan Rule Naming Consistency

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#6049]
We should set some sort of consistency for scan rule naming. The current plan is `*ScanRule`. [Moving away from the current mixed nomenclature: `Test*`, `*Scanner`, `*`.]
- [x] Passive Scan Rules Release (Done in https://github.com/zaproxy/zap-extensions/pull/2456)
- [x] Passive Scan Rules Beta (Done in https://github.com/zaproxy/zap-extensions/pull/2459)
- [x] Passive Scan Rules Alpha (Done in https://github.com/zaproxy/zap-extensions/pull/2460)
- [x] Active Scan Rules Release (Done in https://github.com/zaproxy/zap-extensions/pull/2503)
- [x] Active Scan Rules Beta (Done in https://github.com/zaproxy/zap-extensions/pull/2468)
- [x] Active Scan Rules Alpha (Done in https://github.com/zaproxy/zap-extensions/pull/2467)
- [x] SOAP (Done in https://github.com/zaproxy/zap-extensions/pull/2461)
- [x] Advanced SQLi (Done in https://github.com/zaproxy/zap-extensions/pull/2462)
- [x] [JWT](https://github.com/SasanLabs/owasp-zap-jwt-addon/issues/7) (3rd Party, @preetkaran20) [Marking complete as an issue was created in the 3rd party repo.]
- [x] ILS (Done in https://github.com/zaproxy/zap-extensions/pull/2478)
--
- [x] Document the requirement/preference. [[https://github.com/zaproxy/zaproxy/wiki/DevGuidelines](https://github.com/zaproxy/zaproxy/wiki/DevGuidelines) ??] (Done in https://github.com/zaproxy/zaproxy/wiki/DevGuidelines/aadb5d277438668ba7d52e534e8a7f883c600fa0)

For each addon consider:
- Class names (both scan rules and unit tests).
- Comments (look for "scanner" and "plugin", also check for blogspot URLs [in particular Example scan rules in the Alpha packages]).
- Messages.properties (both key naming and alert/scan rule names, also check refs for blogspot URLs [in particular Example scan rules in the Alpha packages]).
- Help info (look for "scanner" and "plugin").
- Also check for unnecessary constructors in scan rules (a major clue is calls to `super()`).
