### ISSUE TITLE
Add-ons Log4j  2.x Uplift

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#6376]
Align add-ons with core logging changes per:
* https://github.com/zaproxy/zaproxy/pull/6228
* https://github.com/zaproxy/zaproxy/pull/6327

See also: http://logging.apache.org/log4j/2.x/manual/api.html

- [x] accessControl (Done in: https://github.com/zaproxy/zap-extensions/pull/2690)
- [x] alertFilters (Done in: https://github.com/zaproxy/zap-extensions/pull/2687)
- [x] alertReport (Done in: https://github.com/zaproxy/zap-extensions/pull/2681)
- [x] allinonenotes (Done in: https://github.com/zaproxy/zap-extensions/pull/2682)
- [x] ascanrules (Done in: https://github.com/zaproxy/zap-extensions/pull/2673)
- [x] ascanrulesAlpha (Done in: https://github.com/zaproxy/zap-extensions/pull/2689)
- [x] ascanrulesBeta (Done in: https://github.com/zaproxy/zap-extensions/pull/2715)
- [x] authstats (Done in: https://github.com/zaproxy/zap-extensions/pull/2716)
- [x] beanshell (Done in: https://github.com/zaproxy/zap-extensions/pull/2717)
- [x] birtreports (Done in: https://github.com/zaproxy/zap-extensions/pull/2777)
- [x] browserView (Done in: https://github.com/zaproxy/zap-extensions/pull/2718)
- [x] bruteforce (Done in: zaproxy/zap-extensions#2818)
- [x] bugtracker (Done in: https://github.com/zaproxy/zap-extensions/pull/2719)
- [x] callgraph (Done in: https://github.com/zaproxy/zap-extensions/pull/2720)
- [x] codedx (Done in: https://github.com/zaproxy/zap-extensions/pull/2721)
- [x] commonlib (Done in: https://github.com/zaproxy/zap-extensions/pull/2722)
- [x] custompayloads (Done in: zaproxy/zap-extensions#2828)
- ~~customreport~~
- [x] diff (Done in: https://github.com/zaproxy/zap-extensions/pull/2728)
- [x] domxss (Done in: https://github.com/zaproxy/zap-extensions/pull/2729)
- [x] encoder (Done in: https://github.com/zaproxy/zap-extensions/pull/2730)
- ~~exportreport~~
- [x] formhandler (Done in: https://github.com/zaproxy/zap-extensions/pull/2732)
- [x] frontendscanner (Done in: https://github.com/zaproxy/zap-extensions/pull/2733)
- [x] fuzz (Done in: zaproxy/zap-extensions#2804)
- [x] gettingStarted (Done in: https://github.com/zaproxy/zap-extensions/pull/2734)
- [x] graphql (Done in: https://github.com/zaproxy/zap-extensions/pull/2742)
- [x] httpsInfo (Done in: https://github.com/zaproxy/zap-extensions/pull/2775)
- [x] hud (Done in: zaproxy/zap-hud#920)
- [x] imagelocationscanner (Done in: https://github.com/zaproxy/zap-extensions/pull/2674)
- [x] importLogFiles (Done in: https://github.com/zaproxy/zap-extensions/pull/2743)
- [x] importurls (Done in: https://github.com/zaproxy/zap-extensions/pull/2744)
- [x] invoke (Done in: https://github.com/zaproxy/zap-extensions/pull/2724)
- [x] jython (Done in: https://github.com/zaproxy/zap-extensions/pull/2746)
- [x] openapi (Done in: https://github.com/zaproxy/zap-extensions/pull/2767)
- [x] plugnhack (Done in: https://github.com/zaproxy/zap-extensions/pull/2747)
- [x] portscan (Done in: https://github.com/zaproxy/zap-extensions/pull/2748)
- [x] pscanrules (Done in: https://github.com/zaproxy/zap-extensions/pull/2749)
- [x] pscanrulesAlpha (Done in: https://github.com/zaproxy/zap-extensions/pull/2774)
- [x] pscanrulesBeta (Done in: https://github.com/zaproxy/zap-extensions/pull/2680)
- [x] quickstart (Done in: https://github.com/zaproxy/zap-extensions/pull/2776)
- [x] replacer (Done in: https://github.com/zaproxy/zap-extensions/pull/2800)
- [x] requester (Done in: https://github.com/zaproxy/zap-extensions/pull/2750)
- [x] retire (Done in: https://github.com/zaproxy/zap-extensions/pull/2741)
- [x] reveal (Done in: zaproxy/zap-extensions#2801)
- [x] revisit (Done in: zaproxy/zap-extensions#2826)
- [x] saml (Done in: zaproxy/zap-extensions#2823)
- [x] saverawmessage (Done in: https://github.com/zaproxy/zap-extensions/pull/2672)
- [x] savexmlmessage (Done in: zaproxy/zap-extensions#2805)
- [x] scripts (Done in: zaproxy/zap-extensions#2807)
- [x] selenium (Done in: zaproxy/zap-extensions#2806)
- [x] sequence (Done in: zaproxy/zap-extensions#2809)
- [x] simpleexample (Done in: zaproxy/zap-extensions#2808)
- [x] soap (Done in: zaproxy/zap-extensions#2810)
- [x] spiderAjax (Done in: zaproxy/zap-extensions#2811)
- [x] sqliplugin (Done in: zaproxy/zap-extensions#2822)
- [x] sse (Done in: zaproxy/zap-extensions#2814)
- [x] tlsdebug (Done in: zaproxy/zap-extensions#2815)
- [x] todo (Done in: zaproxy/zap-extensions#2816)
- [x] tokengen (Done in: zaproxy/zap-extensions#2820)
- [x] viewstate (Done in: zaproxy/zap-extensions#2817)
- [x] wappalyzer (Done in: https://github.com/zaproxy/zap-extensions/pull/2679)
- ~~wavsepRpt~~
- [x] websocket (Done in: zaproxy/zap-extensions#2813)
- [x] zestAddOn (Done in: zaproxy/zap-extensions#2812)

**Comment by thc202** [comment]
Thanks for raising the issue.

**Comment by thc202** [comment]
Tweaked the issue description, removed the reference to 6276 (just an implementation detail) and removed duplicated reference to 6327.

**Comment by kingthorin** [comment]
In case it might help someone else, or I lose it at some point:

Search > `"\s+\+\s(.*)\s+\+\s+"` (Note this may catch other string concatenations that aren't just in logging statements)
Replace > `{$1}`

**Comment by thc202** [comment]
Closing, all seems to be done.

**Comment by kingthorin** [comment]
Great work team!
