### ISSUE TITLE
Automation framework tracker

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#6461]
Implement a new automation framework

- [ ] Implement initial framework
- [ ] Ajax Spider integration (https://github.com/zaproxy/zap-extensions/pull/2725)
- [ ] New report add-on
- [ ] Report integration
- [ ] Support initial sanity check validation
- [ ] Use for baseline (if hooks not used)
- [ ] Use for full scan (if hooks not used)
- [ ] OpenAPI integration
- [ ] SOAP integration
- [ ] GraphQL integration
- [ ] Use for API scan  (if hooks not used)
- [ ] New Github action which uses this directly
- [ ] Script support (to replace scan hooks)

**Comment by psiinon** [comment]
Updated to break down authentication support

**Comment by so87** [comment]
When you write the documentation, could you please give one example for standard website and an API? showing an example website, and how you would make an automation framework config file on it to do various types of scanning would be incredibly helpful.

for example, this page ends up creating more questions for me than it answers: https://www.zaproxy.org/docs/desktop/addons/automation-framework/

**Comment by kingthorin** [comment]
![image](https://user-images.githubusercontent.com/7570458/141163513-2b648be8-c32d-4a5e-950b-dffd6e39d035.png)

https://www.zaproxy.org/blog/2021-06-15-baseline-scan-changes/

I'm not saying the docs couldn't be better, I'm sure they always can, but there's still lots available to you.

**Comment by psiinon** [comment]
@so87  What questions? If you dont ask them then we cant answer them :P

**Comment by so87** [comment]
first of all thanks for the help. I know i've been commenting alot and with several issues. i appreciate your time.

"-autogenconf <filename> Generate template automation file using the current configuration."
What configuration would this be referring to? A config file(rules/alerts), a context file, or you are supposed to put other automation flags on the command line and it would generate a automation file based off that? If the latter, why would you ever do that?

Also, are there any examples for this automation framework?

Are you expected to?
1. generate the min automation framework config file
2. fill out yaml according to your app
Or is there a better way?

"https://www.zaproxy.org/docs/desktop/addons/automation-framework/job-addons/"
- ok we can install an addon, but how can we use it? Can i see an example for replacer and formhandler?

I would like to think I am not a dumby when it comes to web and configuring tools, but this documentation doesn't enable to configure a web or api scan without asking several questions. maybe it is just because i need to learn zap better and the automation framework is still young. Here is some documentation that i've never had an issue with and i've been able to configure everything i've wanted in sub 5min: https://www.vaultproject.io/docs/configuration 
logs of configuration examples, syntax on the page, clearly defines what the variables are, if they are required or optional.

**Comment by psiinon** [comment]
> What configuration would this be referring to?

The current configuration in the ZAP desktop. If you use the ZAP desktop and change any options then these will be reflected in the yaml file when you use that option.

> Or is there a better way?

You can use the AF GUI in the desktop: https://www.zaproxy.org/docs/desktop/addons/automation-framework/gui/

> ok we can install an addon, but how can we use it?

If the add-on supports the AF then it will be listed here: https://www.zaproxy.org/docs/automate/automation-framework/
You'll notice that neither the replacer or formhandler have AF jobs .. yet
If add-ons dont support the AF then you still might be able to use them, for example the beta and alpha scan rules will be used if you install them in this way and dont specify a scan profile which turns them off. Thats the most useful current usecase in my opinion.

> Here is some documentation that i've never had an issue with ...

We're very happy to hear that.
However we are a very small development team and are extremely busy.
ZAP is a community project and we encourage contributions - if you'ld like to help us out with anything like coding or documentation then we'd be very happy to support you.

**Comment by psiinon** [comment]
I've just added an "Additional jobs" section - feel free to suggest any other jobs that could be added...

**Comment by psiinon** [comment]
Re the Access Control job via https://groups.google.com/g/zaproxy-users/c/vQEtXQt5K-Q/m/RTonJtlQAQAJ

> I think the access control module should have the following parameters
> The expected HTTP code result (ex: 200, 302) and also a regex to find a particular pattern that indicates if a specific message is displayed when reaching an unauthorised URL (for i.e. "You do not have access to this page")
> That would help the efficiency of the access control module :)

**Comment by ArkaprabhaChakraborty** [comment]
Suggestion: AF job for forced-browsing (AF brute-forcing job)

**Comment by ArkaprabhaChakraborty** [comment]
AF job for fuzzing multiple endpoints with different/same payload files

**Comment by kingthorin** [comment]
AF Brute force makes sense.

I think AF Fuzzing has the same challenge as AF API, ex: defining how that should look and be used, especially given the various types of generators/processors.

**Comment by ArkaprabhaChakraborty** [comment]
Well in first place we can have something like the intruder for the fuzzer? With se defined attack types?

**Comment by psiinon** [comment]
Pretty sure we have an open issue for that, but cant see it on a quick search.
But I'm still unclear how fuzzing would be used in the AF?
I've always thought that fuzzing is a manual process.
I guess it can be automated with processors, but it would still come way down the list of things to support in the AF from my point of view...

**Comment by kro29200** [comment]
Hello,
I have the same problem. Is there a workaround ?
