### ISSUE TITLE
Report Generation Tracker

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#6483]
- [x] Release first version
- [ ] Publish competition blog post
- [ ] Support API
- [ ] Redirect core APIs
- [ ] Use add-on in Quick Start cmdline
- [ ] Remove core report functionality
- [ ] Include stats
- [ ] Include full passive scan rule details
- [ ] Include full active scan details
- [ ] Allow arbitrary data to be added
- [ ] Support resources like JS and images
- [ ] Filter on alert fields
- [ ] Load i18n files if present
- [ ] Support custom fields
- [ ] Support report sections

**Comment by psiinon** [comment]
Although I've assigned this to myself anyone else who fancies helping out will be very welcome, just ping me ;)

**Comment by hugobarona** [comment]
It would be extremely useful to include full details in the report, including the passed rules, so in my case, I can render the passed tests during the scan in the final report, after processing it using XSLT and rendering as an NUnit test suite.

**Comment by psiinon** [comment]
@hugobarona thats already supported :) https://github.com/zaproxy/zap-extensions/pull/2839

**Comment by thc202** [comment]
The comment was about the XML report though.

**Comment by psiinon** [comment]
Ha, good point.
We should have new XML & JSON report templates which use the correct encoding and have sections for all supported data. 
I'll add a checkbox for that. We should also think carefully about the format as they are templates many users could end up relying on.

**Comment by hugobarona** [comment]
@psiinon It would be great if some adjustments would be done in the HTML report templates, so it can be easier to read. Currently the sections of alert details are static, and consequently generates a huge HTML report. Maybe it would be good to consider using a collapsable section per alert detail, so the user reading the report could collapse/expand each of the sections, and would improve the report's reading experience.
