### ISSUE TITLE
exim: functionality tracker

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#6579]
Note: While this is assigned, there is no reason that multiple people couldn't take part.

---

Unify import/export functionality into the new [exim](https://github.com/zaproxy/zap-extensions/tree/master/addOns/exim) add-on.

- [x] Migrate [importLogFiles](https://github.com/zaproxy/zap-extensions/tree/master/addOns/importLogFiles) functionality [Done in zaproxy/zap-extensions#3183]
  - [x] Ensure the API properly returns ApiException where appropriate.
  - [x] "Hollow out" existing add-on. Display a warning dialog at install saying to use exim?  Include something about the web APIs. [Done in zaproxy/zap-extensions#3383]
     - (If possible, as of 3183 linked above I've currently simplified the API greatly, however, that's a breaking change.)
- [x] Migrate [importurls](https://github.com/zaproxy/zap-extensions/tree/master/addOns/importurls) functionality [Done in zaproxy/zap-extensions#3178]
  - [x] Ensure the API properly returns ApiException where appropriate.
  - [x] "Hollow out" existing add-on. Display a warning dialog at install saying to use exim? Include something about the web APIs. [Done in zaproxy/zap-extensions#3383]
- [x] Migrate [saverawmessage](https://github.com/zaproxy/zap-extensions/tree/master/addOns/saverawmessage) [Done in zaproxy/zap-extensions#2851 & zaproxy/zap-extensions#2855]
  - [x] "Hollow out" existing add-on. Display a warning dialog at install saying to use exim? [Done in zaproxy/zap-extensions#3381]
- [x] Migrate [savexmlmessage](https://github.com/zaproxy/zap-extensions/tree/master/addOns/savexmlmessage) [Done in zaproxy/zap-extensions#2851 & zaproxy/zap-extensions#2855]
  - [x] "Hollow out" existing add-on. Display a warning dialog at install saying to use exim? [Done in zaproxy/zap-extensions#3381]
- [x] Updated help to include details of HAR functionality. [Done in: zaproxy/zap-extensions#3254]]
- [x] Update API endpoints to use camelCase (Per: https://github.com/zaproxy/zap-extensions/pull/3183#discussion_r728285541) [Done in: zaproxy/zap-extensions#3254]]
- [x] Add stats (Per: https://github.com/zaproxy/zap-extensions/pull/3254#issuecomment-945906835) [Done in: zaproxy/zap-extensions#3348]

Core functionality:
- [x] Export URLs for Context(s) > Context menu item & Reports menu item [Being handled in zaproxy/zaproxy#7285 & zaproxy/zap-extensions#3784]
    - `context.export.urls.menu` ExtensionHistory.java, ExtensionStdMenus.java (PopupMenuExportContextURLs)
- [x] Copy URLs to Clipboard > Context menu item [Being handled in zaproxy/zaproxy#7285 & zaproxy/zap-extensions#3784]
	- `stdexts.copyurls.popup` ExtensionStdMenus.java (PopupMenuCopyUrls)
- [x] Export All URLs to File... > Context menu item & Reports menu item [Being handled in zaproxy/zaproxy#7285 & zaproxy/zap-extensions#3784]
    - `exportUrls.popup` ExtensionHistory.java (PopupMenuExportURLs)
- [x] Export Selected URLs to File... [Being handled in zaproxy/zaproxy#7285 & zaproxy/zap-extensions#3784]
    - `exportUrls.popup.selected` ExtensionHistory.java (PopupMenuExportSelectedURLs)
- [x] PopupMenuExportMessage [Being handled in zaproxy/zaproxy#7285 & zaproxy/zap-extensions#3784]
- [x] PopupMenuExportResponse [Being handled in zaproxy/zaproxy#7285 & zaproxy/zap-extensions#3784]
- [x] Deprecate Core API HAR endpoints. (Done in zaproxy/zaproxy#7433)
    - [x] Update deprecation messages in core, after the exim migration PR is merged. (Done in: https://github.com/zaproxy/zaproxy/pull/7515)
    - [x] Update the [release notes](https://github.com/zaproxy/zap-core-help/blob/main/addOns/help/src/main/javahelp/contents/releases/2.12.0.html) once the deprecation messages are sorted out. (Done in: https://github.com/zaproxy/zap-core-help/pull/462)
- [x] Implement the Core API HAR endpoint functionality in exim. (Done in zaproxy/zap-extensions#3979)

**Comment by kingthorin** [comment]
API deprecation could potentially be handled similarly to: https://github.com/zaproxy/zaproxy/pull/6949/

**Comment by kingthorin** [comment]
Need advice on these.

>  "Hollow out" existing add-on. Display a warning dialog at install saying to use exim?

- Shall we just tell people to use exim?
- Shall we make these depend on exim so that it gets installed?

>Deprecate, and redirect existing API, endpoints. 

- Should we bother deprecating the APIs if the entire add-on is deprecated?
- I'm thinking we should leave the APIs as-is even if the add-ons are hollowed out that way anyone that depends on them can still choose to use them (for now). [In particular for the log import for which the API was greatly simplified.]

**Comment by kingthorin** [comment]
Poke @psiinon @thc202 @ricekot ^ ?

**Comment by thc202** [comment]
> Shall we make these depend on exim so that it gets installed? (Along with a dialog that explains what’s going on)

I like this one, and would do just this. (Also log warn message.)

**Comment by kingthorin** [comment]
What about the web APIs?

Also is there a way to declare an add-on dependency as non-optional?

**Comment by thc202** [comment]
Leave them as is? With the dialogue and warn it should be enough IMO. (Well we should also update the help to point to the new add-on).

If they are add-on dependencies (rather than extension) they are not optional and are always installed.

**Comment by kingthorin** [comment]
Okay perfect, thanks!

**Comment by kingthorin** [comment]
We're starting to get close on this. I'll try to tackle the API Exception tasks in the next few days.

If you have thoughts on what core functionality should be migrated/deprecated please either comment or edit the original post and add task bullets. (Any/all detail helps :grinning:)

**Comment by kingthorin** [comment]
I just noticed that I had already handle the API Exception tasks. So I guess this is ready for an initial release?

I still need some direction/advice on the core stuff.

**Comment by kingthorin** [comment]
Shall I kick off the releases?

**Comment by thc202** [comment]
We could also move the core export options (at least the ones provided in the UI).

**Comment by kingthorin** [comment]
How would we like to go about moving the core items over?

Do we need to deprecate them or can they just be (re)moved? If they're deprecated is there a way for the extension to unhook/unload them? (That might be a one-by-one question.)

**Comment by thc202** [comment]
Safer if deprecated but they can be "moved" already.

**Comment by kingthorin** [comment]
If they're deprecated that's fine but how do we want to prevent duplicate entries int he menus?

**Comment by thc202** [comment]
We talked about adding them to an Export menu (which does not exist yet). For the context menu items, we just need to check if the core class is deprecated to add them or not.

**Comment by kingthorin** [comment]
Perfect, thanks.

**Comment by kingthorin** [comment]
I've added four core items to the list above, let me know what you think. I'm not totally sold on the copy to clipboard one.

Do we want to include Import/Export Context (which is currently in the File menu).

I didn't see any others while I was looking, so let me know if I've missed something.

**Comment by psiinon** [comment]
They look good.
I dont think this add-on should handle the import/export of contexts - those are significantly different.

**Comment by kingthorin** [comment]
I found two more.

**Comment by kingthorin** [comment]
I have this bit of code in exim:
```java
            if (isDeprecated(org.parosproxy.paros.extension.history.PopupMenuExportMessage.class)) {
                getMenuExport().add(getPopupMenuExportMessage());
            }
```

However when trying to load the add-on it bombs:
```
18318 [AWT-EventQueue-0] INFO  org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate - Installing new addon exim v0.2.0
18338 [AWT-EventQueue-0] ERROR org.zaproxy.zap.control.AddOnInstaller - An error occurred while installing the add-on: exim
java.lang.IllegalAccessError: failed to access class org.parosproxy.paros.extension.history.PopupMenuExportMessage from class org.zaproxy.addon.exim.ExtensionExim (org.parosproxy.paros.extension.history.PopupMenuExportMessage is in unnamed module of loader 'app'; org.zaproxy.addon.exim.ExtensionExim is in unnamed module of loader org.zaproxy.zap.control.AddOnClassLoader @1b20fa93)
	at org.zaproxy.addon.exim.ExtensionExim.hook(ExtensionExim.java:76) ~[?:?]
	at org.parosproxy.paros.extension.ExtensionLoader.startLifeCycle(ExtensionLoader.java:797) ~[main/:?]
	at org.zaproxy.zap.control.AddOnInstaller.installAddOnExtensionImpl(AddOnInstaller.java:313) ~[main/:?]
	at org.zaproxy.zap.control.AddOnInstaller.installAddOnExtensions(AddOnInstaller.java:294) ~[main/:?]
	at org.zaproxy.zap.control.AddOnInstaller.install(AddOnInstaller.java:114) ~[main/:?]
	at org.zaproxy.zap.control.AddOnLoader.addAddOnImpl(AddOnLoader.java:489) ~[main/:?]
	at org.zaproxy.zap.control.AddOnLoader.addAddon(AddOnLoader.java:457) ~[main/:?]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.install(ExtensionAutoUpdate.java:1199) ~[main/:?]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.installLocalAddOn(ExtensionAutoUpdate.java:458) ~[main/:?]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.installLocalAddOn(ExtensionAutoUpdate.java:434) ~[main/:?]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.access$2(ExtensionAutoUpdate.java:294) ~[main/:?]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$2.actionPerformed(ExtensionAutoUpdate.java:233) ~[main/:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.AbstractButton.doClick(AbstractButton.java:369) ~[?:?]
	at javax.swing.AbstractButton.doClick(AbstractButton.java:349) ~[?:?]
	at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:975) ~[?:?]
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810) ~[?:?]
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2900) ~[?:?]
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:699) ~[?:?]
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706) ~[?:?]
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706) ~[?:?]
	at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:677) ~[?:?]
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:311) ~[?:?]
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:297) ~[?:?]
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2993) ~[?:?]
	at javax.swing.SwingUtilities.processKeyBindings(SwingUtilities.java:1731) ~[?:?]
	at javax.swing.UIManager$2.postProcessKeyEvent(UIManager.java:1541) ~[?:?]
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:881) ~[?:?]
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139) ~[?:?]
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009) ~[?:?]
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:4892) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]
18355 [AWT-EventQueue-0] INFO  org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate - Finished installing new addon exim v0.2.0
```

I've done the exact same thing for classes in zap packages without issue.

What am I missing?

**Comment by thc202** [comment]
Unrelated to the error, you don't need to check each class individually, one is enough, they are all being deprecated at the same time (if one is the others are guaranteed to be).

**Comment by kingthorin** [comment]
Okay, well I can use that logic/assumption to get around the issue :wink:

**Comment by thc202** [comment]
The cause of the error was mentioned in https://github.com/zaproxy/zaproxy/pull/7285#discussion_r872314711

**Comment by kingthorin** [comment]
I think this can be closed now?

**Comment by thc202** [comment]
There are still things that need to be moved at some point (e.g. core endpoints).

**Comment by kingthorin** [comment]
Do you mean API stuff?

**Comment by thc202** [comment]
Yes.

**Comment by kingthorin** [comment]
Could you add them to the checklist? I'm not sure what I've overlooked.

**Comment by kingthorin** [comment]
I believe this can be closed now that the last of the tasks has been completed?

**Comment by thc202** [comment]
Sounds good.
