### ISSUE TITLE
Callhome tracker

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#6923]
Tracker for the new call home functionality - to replace existing use of bitly (#6016) and implement telemetry.

- [x] Implement new CFU service in AWS
- [x] Change core to use new CFU service #6922
- [x] Monitor CFU service use once its in dev / live docker image
- [x] Monitor CFU service use once its in weekly release / docker image
- [x] Implement new callhome add-on https://github.com/zaproxy/zap-extensions/pull/3312
- [x] Change core to use callhome add-on and make it mandatory
- [x] Implement new News service in AWS
- [x] Change callhome to support News service
- [x] Change Quick Start add-on to use callhome add-on
- [x] Monitor News service use once the add-ons have been published
- [x] Implement new Telemetry service in AWS
- [x] Change callhome to support and call Telemetry service
- [x] Monitor Telemetry service use once the add-on has been published

**Comment by psiinon** [comment]
All done :) Well, apart from enhancements ;)
