### ISSUE TITLE
Update rules to use alert refs

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#7100]
[Rules](https://www.zaproxy.org/docs/alerts/) with multiple examples

- [x] [10020/](https://www.zaproxy.org/docs/alerts/10020/) https://github.com/zaproxy/zap-extensions/pull/3608
- [x] [10032/](https://www.zaproxy.org/docs/alerts/10032/) https://github.com/zaproxy/zap-extensions/pull/3608
- [ ] [40040/](https://www.zaproxy.org/docs/alerts/40040/)
- [ ] [90004/](https://www.zaproxy.org/docs/alerts/90004/)

Rules which should have multiple examples

- [ ] tba

**Comment by sgerlach** [comment]
90018: in fact, this one needs a break, multiple alerts are raised from this rule in a run.
40022: This one I think has two tests (exception, timing) but raises one alert and for some reason has a dynamic name...

**Comment by kingthorin** [comment]
90018 I'm not sure about breaking, it could very well detect multiple SQLi. :shrug:
40022 only does time based but you're right the name handling doesn't respect i18n and statically appends :cry:

**Comment by psiinon** [comment]
Added to the list.
Although I've assigned myself to this issue v happy to have more help if anyone fancies jumping in...

**Comment by sgerlach** [comment]
90028 Should be added here. Adds the method to the Title.

**Comment by kingthorin** [comment]
The generation script task is already done right?

**Comment by thc202** [comment]
Yes, the site is already showing them too, e.g.: https://www.zaproxy.org/docs/alerts/10035-1/
