### ISSUE TITLE
zap-extensions: ComparableResponse candidates

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#7116]
The following add-ons or scan rules could probably benefit from leveraging [ComparableResponse](https://github.com/zaproxy/zap-extensions/pull/3435):

DiceMatcher
- [ ] [LdapInjectionScanRule](https://github.com/zaproxy/zap-extensions/blob/main/addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/LdapInjectionScanRuleUnitTest.java) (alpha)
- [ ] [SourceCodeDisclosureFileInclusionScanRule](https://github.com/zaproxy/zap-extensions/blob/main/addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureFileInclusionScanRule.java) (beta)

Levenshtein
- [ ] [WebCacheDeception](https://github.com/zaproxy/zap-extensions/pull/3635)) (alpha)

HirshbergMatcher
- [ ] [UsernameEnumerationScanRule](https://github.com/zaproxy/zap-extensions/blob/main/addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/UsernameEnumerationScanRule.java) (Beta)

ResponseMatcher
- [ ] [sqliplugin](https://github.com/zaproxy/zap-extensions/tree/main/addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin)

**Comment by thc202** [comment]
The `DiceMatcher` does not have performance issues, we should also take into account that `ComparableResponse` only takes into account HTML/JSON responses.

**Comment by DiogoMRSilva** [comment]
> The `DiceMatcher` does not have performance issues, we should also take into account that `ComparableResponse` only takes into account HTML/JSON responses.

So maybe the `ComparableResponse` should fallback to the DiceMatcher to compare the body when the  content type isn't one of those

**Comment by kingthorin** [comment]
It could probably also easily handle XML.

**Comment by kingthorin** [comment]
Added [GET for POST Active Scan Rule](https://www.zaproxy.org/docs/desktop/addons/active-scan-rules/#get-for-post) as a candidate. (The original issue has been edited.)

**Comment by haanhvu** [comment]
@kingthorin I would love to work on GET for POST scan rule.

**Comment by kingthorin** [comment]
Great!

**Comment by ganesh-dagadi** [comment]
I went through the code and got a high level idea of what `sqliplugin` does. 
1. It sends a clean request and stores the response.
2. Different types of payloads are sent and the response is compared to the original response (This is where responseMatcher is used) and if the original response and current response are not comparable, it means there is a possibility of sql injection.

So based on this, we need to use `ComparableResponse` instead of [getQuickRatio](https://github.com/zaproxy/zap-extensions/blob/3e71ab4d34c47f1bd458d4fd435e854bfbd8bc33/addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/ResponseMatcher.java#L90)

I am thinking of extending `ComparableResponse` in `ResponseMatcher` and performing the comparison.
Am I on the right track?

**Comment by kingthorin** [comment]
IMHO: Do away with ResponseMatcher and just use ComparableResponse.

**Comment by ganesh-dagadi** [comment]
Why is it that the response from the `true` payload is compared to original response, and if they are similar, the `false` payload is sent? Couldn't we just first send a `true` payload, followed by a `false` payload and check the difference between the true and false responses?

                          //send the true payload
                           tempMsg = sendPayload(parameter, reqPayload, true);
                          
                            content = tempMsg.getResponseBody().toString();
                            responseMatcher.setInjectedResponse(content);

                            // Check if the TRUE response is equal or
                            // at less strongly comparable respect to
                            // the Original response value
                            if (responseMatcher.isComparable()) {

                                // Perform again the test's False request
                                tempMsg = sendPayload(parameter, cmpPayload, true);
                                content = tempMsg.getResponseBody().toString();
                                responseMatcher.setInjectedResponse(content);

                                // Now check if the FALSE response is
                                // completely different from the
                                // Original response according to the
                                // responseMatcher ratio criteria
                                if (!responseMatcher.isComparable()) {
                                    // We Found IT!
                                    // Now create the alert message

**Comment by kingthorin** [comment]
Probably just to reduce the number of requests. If it's too similar to the original there's no point trying further 🤷‍♂️

**Comment by ganesh-dagadi** [comment]
Ive done the required changes however, there are no test cases in the plugin. How do I validate that I dint break anything?

**Comment by thc202** [comment]
Add the tests? Does not need to go to 100% coverage.

**Comment by ganesh-dagadi** [comment]
Ok I will add it. Does it have to be on a different pull request and commit from the comparable response changes?

**Comment by thc202** [comment]
No.

**Comment by ganesh-dagadi** [comment]
I encountered two issues while writing the UNION exploitation technique test cases.
1. The `origMsg` to which the returned response from request containing`ORDER BY` is always `<html></html>`. So Comparable response will return a low match ratio for most normal responses. It was the same even before I made any changes.
2. Once `order by` successfully finds the number of columns, Union requests are sent. Here is an example
`id=) UNION ALL SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NRQKHjIvjq',NULL,NULL,NULL,NULL`
Here `NRQKHjIvjq` appears to be a random string which when returned back in the response confirms SQL injection and raises alert. However this is what is expected back from the server `:<random string>:neqkhjlvjg:<random string>`. As you can see the random string on either sides of neqkhjlvjg is not sent to the server in the request. So i have no way of mocking a response containing the random strings.
```
            payload = SQLiPayloadManager.randomString(UNION_MIN_RESPONSE_CHARS, false, null);
            controlToken = SQLiPayloadManager.charsStart + payload + SQLiPayloadManager.charsStop;
            payload = getConcatenatedQuery("\'" + payload + "\'");
            controlToken = controlToken.toLowerCase();

            // Forge the union SQL injection request
            payload = prepareUnionPayload(payload, position, count, uChars, null, false, null);
            payload = paramValue + payload;

            // Perform the request (only payload is sent)
            msg = plugin.sendPayload(paramName, payload, true);
            content = msg.getResponseBody().toString();
            if (content.contains(controlToken)) { //BUT controlToken is expected


```

**Comment by ganesh-dagadi** [comment]
PR submitted

**Comment by kingthorin** [comment]
There's no need to comment about PRs, new PRs have their own notifications.

**Comment by thc202** [comment]
https://github.com/zaproxy/zaproxy/issues/7116#issuecomment-1912303180

You will have to provide more details of your set up,e.g.  what's returning always `<html></html>`?

**Comment by ganesh-dagadi** [comment]
https://github.com/zaproxy/zap-extensions/blob/main/addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLInjectionScanRule.java#L603
 is where the origMsg is initially taking the base message (which I assume is where `<html></html>`is returned). 
https://github.com/zaproxy/zap-extensions/blob/main/addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLInjectionScanRule.java#L636
 is one more place where origMsg is assigned, though in the test cases I ran, the code dint seem to reach this point.

It seems like the plugin is not sending any requests to the target before setting `origMsg` but is using the result of `origMsg` as in here
https://github.com/zaproxy/zap-extensions/blob/main/addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLInjectionScanRule.java#L683

 Here is my test case / setup

```
 @Test
    void shouldRaiseAlertIfTrueAndFalseInBooleanBasedSQLiResponseAreNotSame()
            throws HttpMalformedHeaderException {
        // Given
        String path = "/shouldRaiseAlertIfTrueAndFalseInBooleanBasedSQLiResponseAreNotSame/";
        this.nano.addHandler(
                new NanoServerHandler(path) {
                    boolean isInitialFalseMessageDone = false;
                    boolean isTrueMessageDone = false;
                    boolean isSecondFalseMessageDone = false;

                    @Override
                    protected Response serve(IHTTPSession session) {
                        if (isInitialFalseMessageDone
                                && isSecondFalseMessageDone
                                && isTrueMessageDone) {
                            isInitialFalseMessageDone = false;
                            isSecondFalseMessageDone = false;
                            isTrueMessageDone = false;
                        }
                        if (!isInitialFalseMessageDone) {
                            isInitialFalseMessageDone = true;
                            return newFixedLengthResponse(
                                    Response.Status.INTERNAL_ERROR,
                                    "text/html",
                                    generateFalseMessageForBooleanBasedSQLi());
                        } else if (!isTrueMessageDone) {
                            isTrueMessageDone = true;
                            return newFixedLengthResponse(
                                    Response.Status.OK,
                                    "text/html",
                                    generateTrueMessageForBooleanBasedSQLi());
                        } else if (!isSecondFalseMessageDone) {
                            isSecondFalseMessageDone = true;
                            return newFixedLengthResponse(
                                    Response.Status.INTERNAL_ERROR,
                                    "text/html",
                                    generateFalseMessageForBooleanBasedSQLi());
                        }
                        return newFixedLengthResponse("");
                    }
                });
        // When
        rule.init(this.getHttpMessage(path + "?id="), this.parent);
        rule.scan();
        // Then
        assertEquals(alertsRaised.size(), 1);
    }
```

**Comment by thc202** [comment]
That's right as it uses the original message, which in that test case is given by `getHttpMessage(…)` (which is what has the `<html></html>`). If the scan rule needs other content you should set it to the message before initialising the scan rule.

**Comment by ganesh-dagadi** [comment]
> 2\. Once `order by` successfully finds the number of columns, Union requests are sent. Here is an example
>         `id=) UNION ALL SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NRQKHjIvjq',NULL,NULL,NULL,NULL`
>         Here `NRQKHjIvjq` appears to be a random string which when returned back in the response confirms SQL injection and raises alert. However this is what is expected back from the server `:<random string>:neqkhjlvjg:<random string>`. As you can see the random string on either sides of neqkhjlvjg is not sent to the server in the request. So i have no way of mocking a response containing the random strings.
> 
> 
> ```
>             payload = SQLiPayloadManager.randomString(UNION_MIN_RESPONSE_CHARS, false, null);
>             controlToken = SQLiPayloadManager.charsStart + payload + SQLiPayloadManager.charsStop;
>             payload = getConcatenatedQuery("\'" + payload + "\'");
>             controlToken = controlToken.toLowerCase();
> 
>             // Forge the union SQL injection request
>             payload = prepareUnionPayload(payload, position, count, uChars, null, false, null);
>             payload = paramValue + payload;
> 
>             // Perform the request (only payload is sent)
>             msg = plugin.sendPayload(paramName, payload, true);
>             content = msg.getResponseBody().toString();
>             if (content.contains(controlToken)) { //BUT controlToken is expected
> ```

Please have a look at this. If this is sorted out, I can add another test for ORDER BY Based SQLi.
@kingthorin I would like to work on the GET for POST scan rule too.

**Comment by kingthorin** [comment]
I’d have to dig into the code more to know what the payload manager was doing and where start/stop chats come from. I don’t know off the top of my head.

Set, go for it.

**Comment by ganesh-dagadi** [comment]
This is where I took the code snippet from
https://github.com/zaproxy/zap-extensions/blob/main/addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLiUnionEngine.java#L122

**Comment by biplavoraon** [comment]
For Username Enumeration Scan Rule, what I have understood is that we need to remove Hirshberg Matcher and use Comparable Response instead.
So, we need to remove calculating LCS for responses and just do similarity comparisons by using Comparable Response threshold.

Please let me know if my understanding is correct?

**Comment by kingthorin** [comment]
Yup exactly.

**Comment by biplavoraon** [comment]
Regarding the implementation, should we compare in the following order:
1. n responses for valid username
2. n responses for `invalidUsername`
3. finally, compare the nth response of the valid username with the nth response of the `invalidUsername`.

@kingthorin Could you please assign this to me?

**Comment by kingthorin** [comment]
For my two cents I'd just do the replacement for now. If there's a reason to change or refine the logic further that should be a second PR.

**Comment by kingthorin** [comment]
You probably have to mock part of it for the test(s). There should be examples in other scan rule unit tests.

**Comment by kingthorin** [comment]
@ganesh-dagadi / @biplavoraon I guess you didn't end-up working on these?

**Comment by ganesh-dagadi** [comment]
@kingthorin
 I have a PR for the SQLi plugin. [zaproxy/zap-extensions#5253](https://github.com/zaproxy/zap-extensions/pull/5253)

Kindly have a look.

**Comment by kingthorin** [comment]
Thanks, sorry I lost track.

**Comment by kingthorin** [comment]
You can change the logic if necessary as long as the end result is the same.

**Comment by ganesh-dagadi** [comment]
@kingthorin 
Really sorry I am unable to work on this at the moment. kindly un-assign me.
