### ISSUE TITLE
Default thread to number of processors

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#7663]
Increasing the number of threads makes a significant performance improvement, and defaulting to the number of available processors seems to be the best option.
This can be found out using `Runtime.getRuntime().availableProcessors()`.

Tools to change:

- [x] Active scanner - #7664
- [x] Passive Scanner - #7664
- [x] Std Spider - zaproxy/zap-extensions#4326
- [x] Ajax Spider - zaproxy/zap-extensions#4326
- [x] Forced Browse - zaproxy/zap-extensions#4326
- [x] Fuzzer - zaproxy/zap-extensions#4326
- [x] Port Scan - zaproxy/zap-extensions#4326
- [x] Param Digger - zaproxy/zap-extensions#4326

**Comment by kingthorin** [comment]
Is Param Digger threaded?

**Comment by thc202** [comment]
It is.

**Comment by kingthorin** [comment]
Added.

**Comment by thc202** [comment]
@psiinon can be closed?

**Comment by psiinon** [comment]
Yes 😁
