### ISSUE TITLE
Identify or Create Authentication Example Pages

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#7789]
This is a tracker issue which covers the identification or creation of test login pages which can be used for ZAP integration tests.

We want ZAP to be able to handle as many authentication options as easily for the user as possible. For that we need good examples we can use for any implementation and integration testing.

Standalone examples:

- [ ] Simple user + password form (no SSO) - @AliAbdollahiii
- [ ] Simple user + password form with arbitrary other fields (checkboxes, pulldowns, no SSO) - @AliAbdollahiii
- [ ] Simple user, submit then password forms (no SSO)
- [ ] (todo add more)

SSO examples (alphabetic order):

- [ ] Auth0 - @ankush-jain-akto 
- [ ] Azure Active Directory
- [ ] Keycloak - @uxdom
- [ ] Okta
- [ ] (todo add more)

Add a comment to add more suggestions.

The best case is identifying online examples that have published credentials which are reliably maintained. We would just need:

- The URL
- The credentials

If the authentication method has a standard way of handling session management then another page which is requested after login which can be used to tell if the user is logged in would be very useful as well.

If there are no suitable online examples available then new test pages should be created in the https://github.com/zaproxy/auth-examples repo.

The requirements are:

- Packaged in docker
- Complete setup instructions
- Easy to automate
- Easy to maintain

If you would like to work on any one of these then add a comment stating which one you would like to work on.

**Comment by theinfosecguy** [comment]
Just to be clear, do we need a single application for each use case or a single application with multiple pages to handle all use cases?

Also, https://github.com/zaproxy/auth-examples will be a mono repo (backend & frontend), right?

**Comment by psiinon** [comment]
@theinfosecguy A single app would be ideal but might be impractical. We'd like to minimise the tech involved so fewer languages and frameworks would be better, but we realise we may well need a range of them.
That will be a mono repo for the backend and frontend of all of the apps (if theres more than one).
Suggestions on how to structure the repo and which techs are best appreciated 😁

**Comment by thc202** [comment]
Existing example/demo apps are preferred than writing new ones though.

**Comment by ankush-jain-akto** [comment]
Hi @psiinon - I would love to help with Auth0. Assign me please 🙋‍♂️. 

I would also suggest to add password-less logins. For example [Email+OTP] or [Phone+OTP]

**Comment by uxdom** [comment]
Hi @psiinon. Want to contribute to the Keycloak.

**Comment by AliAbdollahiii** [comment]
Hey @kingthorin 
I want to contribute to:

- Simple user + password form (no SSO)

- Simple user + password form with arbitrary other fields (checkboxes, pulldowns, no SSO)

Thanks

**Comment by psiinon** [comment]
Title tweaked as some people thought it was for creating ZAP scripts to handle auth😉

**Comment by leonardoadame** [comment]
Will like to scan my device

**Comment by psiinon** [comment]
@leonardoadame questions are best asked on the ZAP User Group: https://groups.google.com/group/zaproxy-users
And we will need to know a lot more information.

**Comment by Sam-LearnsToCode** [comment]
> Simple user, submit then password forms (no SSO)

correct me if I am wrong but do you expect  two different forms one for creating username then another for password ?
If yes I'd like to work on this else can you explain what is expected ?

**Comment by kingthorin** [comment]
I have mixed feelings. "Real" examples will always feel better to end users. However, we've also seen that "real" integration tests can be a headache with other infrastructure going down or changing subtly. For the time being I'm fine with us focusing on `dev` implementations.

**Comment by AliAbdollahiii** [comment]
Hey @kingthorin 
I just wanted to drop the examples but I think I don't have access to upload as folder/files.
The examples look like these:
1. https://github.com/AliAbdollahiii/1simpleauth
2. https://github.com/AliAbdollahiii/simpleauth-fields
As you mentioned, the examples also meet the requirements:

-     Packaged in docker
-     Complete setup instructions
-     Easy to automate
-     Easy to maintain

**Comment by andremralves** [comment]
> Hey @kingthorin I just wanted to drop the examples but I think I don't have access to upload as folder/files. The examples look like these:

The problem is that you should've created a fork of [auth-examples](https://github.com/zaproxy/auth-examples) first. Then you add those folders into the fork and make the PR.

**Comment by thc202** [comment]
They did create a fork and created a PR also: zaproxy/auth-examples#2.

**Comment by thc202** [comment]
https://github.com/zaproxy/zaproxy/issues/7789#issuecomment-1559315526

Same here.

**Comment by uxdom** [comment]
@kingthorin I have created a draft pull here https://github.com/zaproxy/auth-examples/pull/5 let me know if this the right way we want to demo examples. Thanks!

**Comment by thc202** [comment]
The repo https://github.com/zaproxy/auth-examples is now archived.
