### ISSUE TITLE
Merge Import dialogs for API import add-ons

### ISSUE THREAD

**Issue by ricekot** [zaproxy/zaproxy#7913]
### Is your feature request related to a problem? Please describe.

Merge the "Import from the local file system" and "Import from a URL" dialogs into one for the following add-ons:
- [x] [openapi](https://github.com/zaproxy/zap-extensions/tree/main/addOns/openapi)
- [x] [soap](https://github.com/zaproxy/zap-extensions/tree/main/addOns/soap)
- [x] [graphql](https://github.com/zaproxy/zap-extensions/tree/main/addOns/graphql)
- [ ] [postman](https://github.com/zaproxy/zap-extensions/tree/main/addOns/postman)

### Describe the solution you'd like

There should be a single import dialog for each add-on, e.g. "Import a  GraphQL Schema", or "Import an OpenAPI definition".

The changes should be restricted only to the GUI; the API and CLI should continue to offer separate file and URL import options.

### Describe alternatives you've considered

N/A

### Additional context

As discussed in IRC.

### Would you like to help fix this issue?

- [X] Yes
