### ISSUE TITLE
Release 2.13.0

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#7924]
### Pre release

- [x] Update dependencies - these can be checked using the [zaproxy](https://github.com/zaproxy/zaproxy) `dependencyUpdates` gradle task zaproxy/zaproxy#7930
- [x] Update the [gettingStarted](https://github.com/zaproxy/zap-extensions/tree/main/addOns/gettingStarted) ODT document and regenerate the PDF. zaproxy/zap-extensions#4711
- [x] Update the [MacOS JRE](https://github.com/zaproxy/zaproxy/blob/main/buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts). zaproxy/zaproxy#7927
- [x] Update the [MacOS Copyright statement](https://github.com/zaproxy/zaproxy/blob/main/zap/src/main/macOS/OWASP%20ZAP.app/Contents/Info.plist). zaproxy/zaproxy#7927
- [x] Update [Constant](https://github.com/zaproxy/zaproxy/blob/main/zap/src/main/java/org/parosproxy/paros/Constant.java)#VERSION_TAG. zaproxy/zaproxy#7931
- [x] Add and use a [Constant](https://github.com/zaproxy/zaproxy/blob/main/zap/src/main/java/org/parosproxy/paros/Constant.java).upgradeFrom`<version>`() method. zaproxy/zaproxy#7931
- [x] Update [common-user-agents.txt](https://github.com/zaproxy/zap-extensions/blob/main/addOns/network/src/main/resources/org/zaproxy/addon/network/internal/client/common-user-agents.txt) and [DEFAULT_DEFAULT_USER_AGENT](https://github.com/zaproxy/zap-extensions/blob/main/addOns/network/src/main/java/org/zaproxy/addon/network/ConnectionOptions.java). zaproxy/zap-extensions#4707
- [x] Create help release page zaproxy/zap-core-help#506
  - Development / bug fix issue links can be generated using the [zap-admin](https://github.com/zaproxy/zap-admin) `generateReleaseNotes` task. 
  - Library changes can be determined by diffing [LEGALNOTICE.md](https://github.com/zaproxy/zaproxy/blob/main/LEGALNOTICE.md) with the version at the previous release.
- [x] Create the [zap-admin](https://github.com/zaproxy/zap-admin) version and news files zaproxy/zap-admin#973
- [x] Prepare blog post https://github.com/zaproxy/zaproxy-website/pull/1944

### Release Process

- [x] Run the workflow [Prepare Release Main Version](https://github.com/zaproxy/zaproxy/actions/workflows/prepare-release-main-version.yml),     to prepare the release. It creates a pull request updating the version;
- [x] Finish the following tasks in the pull request:
  - [x] Release add-ons.
  - [x] Update main add-ons declared in [main-add-ons.yml](https://github.com/thc202/zaproxy/blob/main/zap/src/main/main-add-ons.yml):
     - [x] Add new add-ons.
     - [x] Remove add-ons no longer needed.
     - [x] Update add-ons with the task mentioned in `main-add-ons.yml`.
  - [x] Update [SECURITY.md](https://github.com/zaproxy/zaproxy/blob/main/SECURITY.md) to mention the latest version.
  - [x] Update the version of the snap and the source file in [snapcraft.yaml](https://github.com/zaproxy/zaproxy/blob/main/snap/snapcraft.yaml).
- [x] Merge the pull request, to create the tag and the draft release (done by [Release Main Version](https://github.com/zaproxy/zaproxy/actions/workflows/release-main-version.yml));
- [x] Verify the draft release.
- [x] Publish the release.
- [x] Regenerate and publish the Weekly and Live releases.
- [x] Update the [Linux Repos](https://software.opensuse.org/download.html?project=home%3Acabelo&package=owasp-zap)

### Post Release

- [x] Publish blog post
- [x] Update latest News file to point to blog / release notes?
- [x] Announce on
  - [x] ZAP User and Dev groups
  - [x] @zaproxy twitter account
  - [x] OWASP Slack
- [x] Release client APIs
  - [x] [Java](https://github.com/zaproxy/zap-api-java/blob/main/RELEASING.md)
  - [x] [Python](https://github.com/zaproxy/zap-api-python/blob/master/RELEASING.md)
- [x] Update major projects using ZAP
  - [x] Kali - [new issue](https://bugs.kali.org/) https://bugs.kali.org/view.php?id=8388
  - [x] [Flathub](https://github.com/flathub/org.zaproxy.ZAP)
  - [x] [Snap](https://github.com/zaproxy/zaproxy/tree/main/snap)
    - [x] Run the workflow [Release Snap](https://github.com/zaproxy/zaproxy/actions/workflows/release-snap.yml).
- [ ] Update 3rd Party Package Managers 
  - [x] Homebrew - [owasp-zap.rb](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/owasp-zap.rb) https://github.com/Homebrew/homebrew-cask/pull/150880
  - [x] Scoop - [zaproxy.json](https://github.com/ScoopInstaller/Extras/blob/master/bucket/zaproxy.json) https://github.com/ScoopInstaller/Extras/pull/11577
  - [ ] Chocolatey - [zap](https://community.chocolatey.org/packages/zap) - have commented on that page
- [x] Update [bugcrowd](https://bugcrowd.com/owaspzap) scope

**Comment by kingthorin** [comment]
Doh, duped the Kali issue, will close mine.

**Comment by thc202** [comment]
I think this can be closed now, there's only one pending 3rd-party update.

**Comment by kingthorin** [comment]
Okay with me
