### ISSUE TITLE
Client add-on issue tracker

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#8020]
Required for first release?

- [ ] Client events not recorded for Ajax Spider
- [ ] Option to enable/disable client events

Important but not required for first release?

- [ ] Have to manually enable for every site in Firefox
- [ ] Chrome headless does not support extensions

**Comment by aryangupta701** [comment]
Hii can you please assign this issue to me?

**Comment by aryangupta701** [comment]
chrome headless does support extension by the way. we have to use
 `--headless-new` argument. We are already using that in test cases for the browser extension. If we can do that there I think it is possible in java too. 
I will research about it and inform you.

**Comment by thc202** [comment]
That's already being done in Java too, both Selenium add-on and Zest (e.g.: https://github.com/zaproxy/zap-extensions/blob/7ef49446c742a7308a385ec6293f75f25c8392b1/addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java#L1004)

**Comment by psiinon** [comment]
Have confirmed it works with Chrome headless 😁

**Comment by psiinon** [comment]
All done
