### ISSUE TITLE
Release 2.14.0

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#8096]
### Pre release

Based on https://github.com/zaproxy/zaproxy/blob/main/RELEASING.md

- [x] Update dependencies - these can be checked using the [zaproxy](https://github.com/zaproxy/zaproxy) `dependencyUpdates` gradle task #8097
- [x] Update the [gettingStarted](https://github.com/zaproxy/zap-extensions/tree/main/addOns/gettingStarted) ODT document and regenerate the PDF. https://github.com/zaproxy/zap-extensions/pull/4959
- [x] Update the [MacOS JRE](https://github.com/zaproxy/zaproxy/blob/main/buildSrc/src/main/kotlin/org/zaproxy/zap/distributions.gradle.kts). #8098
- [x] Update the [MacOS Copyright statement](https://github.com/zaproxy/zaproxy/blob/main/zap/src/main/macOS/ZAP.app/Contents/Info.plist). Already current year.
- [x] Update [Constant](https://github.com/zaproxy/zaproxy/blob/main/zap/src/main/java/org/parosproxy/paros/Constant.java)#VERSION_TAG. #8106
- [x] Add and use a [Constant](https://github.com/zaproxy/zaproxy/blob/main/zap/src/main/java/org/parosproxy/paros/Constant.java).upgradeFrom`<version>`() method. Not required.
- [x] Update [common-user-agents.txt](https://github.com/zaproxy/zap-extensions/blob/main/addOns/network/src/main/resources/org/zaproxy/addon/network/internal/client/common-user-agents.txt) and [DEFAULT_DEFAULT_USER_AGENT](https://github.com/zaproxy/zap-extensions/blob/main/addOns/network/src/main/java/org/zaproxy/addon/network/ConnectionOptions.java). zaproxy/zap-extensions#4961
- [x] Publish a SNAPSHOT of core and update the main add-ons to use it.
- [x] Create help release page zaproxy/zap-core-help#524
  - Development / bug fix issue links can be generated using the [zap-admin](https://github.com/zaproxy/zap-admin) `generateReleaseNotes` task.
  - Library changes can be determined by diffing [LEGALNOTICE.md](https://github.com/zaproxy/zaproxy/blob/main/LEGALNOTICE.md) with the version at the previous release.
- [x] Create the [zap-admin](https://github.com/zaproxy/zap-admin) version and news files https://github.com/zaproxy/zap-admin/pull/1036
- [x] Prepare blog post @psiinon zaproxy/zaproxy-website#2182

### Release Process

- [x] Run the workflow [Prepare Release Main Version](https://github.com/zaproxy/zaproxy/actions/workflows/prepare-release-main-version.yml),     to prepare the release. It creates a pull request updating the version;
- [x] Finish the following tasks in the pull request:
  - [x] Update latest ZapVersions file in [build.gradle.kts](https://github.com/zaproxy/zap-admin/blob/master/build.gradle.kts)
  - [x] Release add-ons.
  - [x] Update main add-ons declared in [main-add-ons.yml](https://github.com/zaproxy/zaproxy/blob/main/zap/src/main/main-add-ons.yml):
     - [x] Add new add-ons.
     - [x] Remove add-ons no longer needed.
     - [x] Update add-ons with the task mentioned in `main-add-ons.yml`.
- [x] Merge the pull request, to create the tag and the draft release (done by [Release Main Version](https://github.com/zaproxy/zaproxy/actions/workflows/release-main-version.yml));
- [x] Verify the draft release.
- [x] Publish the release.
- [x] Regenerate and publish the Weekly and Live releases.
- [x] Update the [Linux Repos](https://software.opensuse.org/download.html?project=home%3Acabelo&package=owasp-zap)
- [x] Update the stats scripts [github.py](https://github.com/zapbot/zap-mgmt-scripts/blob/master/stats/github.py) and [zap_services.py](https://github.com/zapbot/zap-mgmt-scripts/blob/master/stats/zap_services.py)

Once published the [Handle Release](https://github.com/zaproxy/zaproxy/actions/workflows/handle-release.yml) workflow
will trigger the update of the marketplace with the new release, it will also create a pull request preparing the next
development iteration.

### Localized Resources

The resources that require localization (e.g. `Messages.properties`, `vulnerabilities.xml`) are uploaded to the ZAP projects in
[Crowdin](https://crowdin.com/) when the main release is released, if required (for pre-translation) the resources can be uploaded manually
at any time by running the workflow [Crowdin Upload Files](https://github.com/zaproxy/zaproxy/actions/workflows/crowdin-upload-files.yml).

The resulting localized resources are added/updated in the repository periodically (through a workflow in the
[zap-admin repository](https://github.com/zaproxy/zap-admin/)).

### Post Release

- [x] Publish blog post
- [x] Update latest News file to point to blog / release notes?
- [x] Announce on
  - [x] ZAP User and Dev groups
  - [x] @zaproxy twitter account
  - [x] OWASP Slack
- [x] Update and release client APIs
  - [x] [Java](https://github.com/zaproxy/zap-api-java/blob/main/RELEASING.md)
  - [x] [Python](https://github.com/zaproxy/zap-api-python/blob/master/RELEASING.md)
  - [x] NodeJS
- [x] Update major projects using ZAP
  - [x] Kali - [8502](https://bugs.kali.org/view.php?id=8502) - Might only be visible to kingthorin
  - [x] [2.14 PR](https://github.com/flathub/org.zaproxy.ZAP/pull/12)
  - [x] [Snap](https://github.com/zaproxy/zaproxy/tree/main/snap)
    - [x] Run the workflow [Release Snap](https://github.com/zaproxy/zaproxy/actions/workflows/release-snap.yml).
- [x] Update 3rd Party Package Managers 
  - [x] Homebrew - [owasp-zap.rb](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/owasp-zap.rb)
  - [x] Scoop - [zaproxy.json](https://github.com/ScoopInstaller/Extras/blob/master/bucket/zaproxy.json)
  - [x] Chocolatey - [zap](https://community.chocolatey.org/packages/zap)
- [x] Update [bugcrowd](https://bugcrowd.com/owaspzap) scope

**Comment by kingthorin** [comment]
```console
zaproxy/kali-rolling 2.14.0-0kali1 all [upgradable from: 2.13.0-0kali1]
```

**Comment by kingthorin** [comment]
Is the Java API client still pending?

**Comment by thc202** [comment]
Yes and NodeJS (to support file upload), working on both.
