### ISSUE TITLE
Link website alert pages <-> help

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#8189]
There are currently no links between the alert pages and the alert help pages.
This is a shame as the alert help pages often include useful information such as how the alerts work and how they can be tuned.

For example:

- https://www.zaproxy.org/docs/alerts/90020/
- https://www.zaproxy.org/docs/desktop/addons/active-scan-rules/#command-injection

Proposed solution:

The Alert help should link to the alert pages using a standard format.
Suggestion is to include a link immediately after the alert heading:

```html
Alert ID: <a href="https://www.zaproxy.org/docs/alerts/90020/">90020</a>.
```

The rules should extend a common interface per add-on that has a method like:
```java
     default String getHelpLink(int id) {
        return "https://www.zaproxy.org/docs/desktop/addons/active-scan-rules/#id-" + id;
    }
```
See [CommonActiveScanRuleInfo](https://github.com/zaproxy/zap-extensions/blob/b1a951ee20e58805fa8f9ee70ec0ec523858d727/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CommonActiveScanRuleInfo.java) for the full example.

This will be optional and not part of any interface for now (so we dont have to depend on core changes).
It will be used by the script we use to generate the help pages - that already makes heavy use of reflection anyway..

The changes do not have to be all made at the same time - they can be broken down into multiple PRs, e.g.

- [x] Active scan rules - zaproxy/zap-extensions#5180
- [x] Active scan rules (beta) - zaproxy/zap-extensions#5268
- [x] Active scan rules (alpha) - zaproxy/zap-extensions#5156
- [x] Passive scan rules - zaproxy/zap-extensions#5293
- [x] Passive scan rules (beta) - zaproxy/zap-extensions#5249
- [x] Passive scan rules (alpha) - zaproxy/zap-extensions#5094
- [x] Image Location Scanner - zaproxy/zap-extensions#5258
- [x] Websocket passive scan rules - zaproxy/zap-extensions#6389
- [x] GraphQL - zaproxy/zap-extensions#5298
- [x] SOAP - zaproxy/zap-extensions#5302
- [x] RetireJS - zaproxy/zap-extensions#5258
- [x] Access Control - zaproxy/zap-extensions#5302

Additional changes needed:

- [x] Update alert page generation script https://github.com/zaproxy/zap-admin/pull/1068
- [x] Update alert page templates https://github.com/zaproxy/zaproxy-website/pull/2264

These are easy changes, and there's no problem with multiple people working on this - just comment if you plan to work on it saying which ones you are going to work on..

**Comment by psiinon** [comment]
For example, taking the [Passive scan rules (alpha)](https://www.zaproxy.org/docs/desktop/addons/passive-scan-rules-beta/) rules you would need to:

- Edit all of the rule classes in [ascanrulesAlpha](https://github.com/zaproxy/zap-extensions/tree/main/addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha) to add the `getHelpLink()` method mentioned above - the links can all be found on https://www.zaproxy.org/docs/desktop/addons/passive-scan-rules-alpha/
- Edit [ascanalpha.html](https://github.com/zaproxy/zap-extensions/blob/main/addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html) to add the `Alert ID:..` links mentioned above

**Comment by amitpanwar789** [comment]
ok i will work on it for passive scan rules (alpha) , but @psiinon , you taking example of passive scan rules and saying we need to edit all of the rule classes of [ascanrulesAlpha](https://github.com/zaproxy/zap-extensions/tree/main/addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha), I am not sure but maybe it is be [pscanalpha](https://github.com/zaproxy/zap-extensions/tree/main/addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha). and one more thing is, what I understand is for example for Base64 Disclosure , we need to add 
```
public String getHelpLink() {
return "https://www.zaproxy.org/docs/desktop/addons/passive-scan-rules-alpha/#base64-disclosure"
}
```
method in [Base64Disclosure.java](https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java) and add Alert ID:< a href="https://www.zaproxy.org/docs/alerts/10094-3" > in [pscanalpha.html](https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html)

**Comment by psiinon** [comment]
Oh, my bad - I mixed up the add-ons, I'l lcorrect that now..

**Comment by PariharAditya** [comment]
can I work on Passive Scan Rules Beta

**Comment by kingthorin** [comment]
We've been trying to have people just tackle one or a small subset at a time. That keeps the PRs easy to review and merge. Just let us know the IDs you're interested in tackling.

**Comment by PariharAditya** [comment]
> We've been trying to have people just tackle one or a small subset at a time. That keeps the PRs easy to review and merge. Just let us know the IDs you're interested in tackling.

Ok, I would work on ID-10049.
So, do I've to add an id in the HTML header section and create a method of the respective class ?
example 
<H2 id="id-10049">Content Cacheability</H2>
and in the "https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/CacheableScanRule.java"
ToDo is 
public String getHelpLink() {
        return "https://www.zaproxy.org/docs/desktop/addons/passive-scan-rules-beta/#content-cachebility";
    }

**Comment by kingthorin** [comment]
Oh I spoke out of turn, I had this mixed up with #8262.

Yes that's what you need to do, and yes you can tackle all of "Passive Scan Rules Beta"

**Comment by PariharAditya** [comment]
> Oh I spoke out of turn, I had this mixed up with #8262.
> 
> Yes that's what you need to do, and yes you can tackle all of "Passive Scan Rules Beta"
> 
> Edit: I'll fix-up the original issue description too, the link in the getHelpLink method should use #<plugin_id> so in your example
> 
> ```java
> public String getHelpLink() {
>     return "https://www.zaproxy.org/docs/desktop/addons/passive-scan-rules-beta/#10049";
> }
> ```

ok sir

**Comment by kingthorin** [comment]
@PariharAditya someone else just reminded me you can do it as an interface like this: https://github.com/zaproxy/zap-extensions/blob/main/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CommonActiveScanRuleInfo.java and then just have the rules implement it. (Look as the ascanrules add-on for examples.)

**Comment by PariharAditya** [comment]
> @PariharAditya someone else just reminded me you can do it as an interface like this: https://github.com/zaproxy/zap-extensions/blob/main/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CommonActiveScanRuleInfo.java and then just have the rules implement it. (Look as the ascanrules add-on for examples.)
> 
> Similar pscanrulesAlpha: https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/CommonPassiveScanRuleInfo.java

yup I've gone through it earlier so instead of a particular ID I've to do it for all classes in a particular scan rule section

**Comment by kingthorin** [comment]
Great, thanks.

**Comment by thedudeontitan** [comment]
Hello, can i work on the Active scan rules (beta)?

**Comment by kingthorin** [comment]
@thedudeontitan go for it.

**Comment by thedudeontitan** [comment]
Hey I wanted to work on the graphQL part in this issue, where should i put the alert ID link in the html, only the sub alerts are mentioned on the (addons page)[https://www.zaproxy.org/docs/desktop/addons/graphql-support/alerts/].

**Comment by kingthorin** [comment]
Assigned, not sure about your other question:
![image](https://github.com/zaproxy/zaproxy/assets/7570458/5bab9c5d-e150-4c64-84d7-a33929064fde)

**Comment by kingthorin** [comment]
Does the websocket add-on need any changes to be able to use script metadata? Were we waiting on targeting Java 17 to switch them?

**Comment by MZ-AD** [comment]
If this issue is not assigned to anyone, you can assign it to me so  that I can start digging up

**Comment by kingthorin** [comment]
The websocket passive scan scripts are here: https://github.com/zaproxy/zap-extensions/tree/main/addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive

They should be updated to leverage metadata like these: https://github.com/zaproxy/community-scripts/tree/main/passive

And include help links to: https://github.com/zaproxy/zap-extensions/blob/main/addOns/websocket/src/main/javahelp/org/zaproxy/zap/extension/websocket/resources/help/contents/pscanrules.html

In which the relevant headings should have id attributes added with the relevant rule IDs.

**Comment by kingthorin** [comment]
@MZ-AD you could break it into two PRs. Since you're switching the scripts/rules to use the yaml metadata and doing the linking, it's not a totally trivial change set so it might be more practical to keep the PR(s) smaller.

**Comment by MZ-AD** [comment]
Yes, I'm on it

> [@MZ-AD](https://github.com/MZ-AD) are you tackling this?

**Comment by YashArote** [comment]
Can I work on this, if its not assigned

**Comment by kingthorin** [comment]
Based on the last few updates I believe all that's left is the websocket scripts. Yes you can tackle it. Look through the history and linked PRs, and don't try to boil the ocean it can be done in pieces.

There's a chance other rules are outstanding but someone would have to dig to double check.

**Comment by kingthorin** [comment]
Dev guide here: https://www.zaproxy.org/docs/developer/

**Comment by YashArote** [comment]
So what I need to do in websocket scripts is to implement getMetaData function, update help links and alert links with proper ids right?

**Comment by kingthorin** [comment]
Yes, if the IDs aren't obvious they should be listed here: https://github.com/zaproxy/zaproxy/blob/main/docs/scanners.md

**Comment by kingthorin** [comment]
As far as I can tell this has been completed.
