### ISSUE TITLE
Update alert http links

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#8262]
Many of the alerts still have http links.
Where possible we should update these to their https equivalents, but it does mean checking there is an https equivalent.
The alerts with http links are as follows.
Although these are links to the website the alert pages are generated, so its actually the code that needs to be changed.

- [x] https://www.zaproxy.org/docs/alerts/0/ zaproxy/zap-extensions#5177
- [x] https://www.zaproxy.org/docs/alerts/3-1/ zaproxy/zap-extensions#5205
- [x] https://www.zaproxy.org/docs/alerts/3-2/ zaproxy/zap-extensions#5205
- [x] https://www.zaproxy.org/docs/alerts/3-3/ zaproxy/zap-extensions#5205
- [x] https://www.zaproxy.org/docs/alerts/6/ zaproxy/zap-extensions#5177 
- [x] https://www.zaproxy.org/docs/alerts/7/ zaproxy/zap-extensions#5177
- [x] https://www.zaproxy.org/docs/alerts/41/ 
- [x] https://www.zaproxy.org/docs/alerts/42/
- [x] https://www.zaproxy.org/docs/alerts/43/ zaproxy/zap-extensions#5177
- [x] https://www.zaproxy.org/docs/alerts/10019/ zaproxy/zap-extensions#5184
- [x] https://www.zaproxy.org/docs/alerts/10021/ zaproxy/zap-extensions#5184
- [x] https://www.zaproxy.org/docs/alerts/10029/ zaproxy/zap-extensions#5205
- [x] https://www.zaproxy.org/docs/alerts/10031/ zaproxy/zap-extensions#5205
- [x] https://www.zaproxy.org/docs/alerts/10032-4/ zaproxy/zap-extensions#5263
- [x] https://www.zaproxy.org/docs/alerts/10032-5/ zaproxy/zap-extensions#5263
- [x] https://www.zaproxy.org/docs/alerts/10035/ zaproxy/zap-extensions#5201
- [x] https://www.zaproxy.org/docs/alerts/10036-1/ zaproxy/zap-extensions#5205
- [x] https://www.zaproxy.org/docs/alerts/10036-2/ zaproxy/zap-extensions#5205
- [x] https://www.zaproxy.org/docs/alerts/10037/ zaproxy/zap-extensions#5204
- [x] https://www.zaproxy.org/docs/alerts/10038-1/ zaproxy/zap-extensions#5205
- [x] https://www.zaproxy.org/docs/alerts/10038-2/ zaproxy/zap-extensions#5205
- [x] https://www.zaproxy.org/docs/alerts/10038-3/ zaproxy/zap-extensions#5205
- [x] https://www.zaproxy.org/docs/alerts/10043/ zaproxy/zap-extensions#5220
- [x] https://www.zaproxy.org/docs/alerts/10045/ zaproxy/zap-extensions#5177
- [x] https://www.zaproxy.org/docs/alerts/10047/ zaproxy/zap-extensions#5220
- [x] https://www.zaproxy.org/docs/alerts/10048/ zaproxy/zap-extensions#5242
- [x] https://www.zaproxy.org/docs/alerts/10050/ zaproxy/zap-extensions#5216
- [x] https://www.zaproxy.org/docs/alerts/10051/ zaproxy/zap-extensions#5236
- [x] https://www.zaproxy.org/docs/alerts/10053/ zaproxy/zaproxy-website#2389
- [x] https://www.zaproxy.org/docs/alerts/10055-1/ zaproxy/zap-extensions#5205 
- [x] https://www.zaproxy.org/docs/alerts/10055-2/ zaproxy/zap-extensions#5205
- [x] https://www.zaproxy.org/docs/alerts/10055-3/ zaproxy/zap-extensions#5205
- [x] https://www.zaproxy.org/docs/alerts/10055-4/ zaproxy/zap-extensions#5205
- [x] https://www.zaproxy.org/docs/alerts/10055-5/ zaproxy/zap-extensions#5205 
- [x] https://www.zaproxy.org/docs/alerts/10055-6/ zaproxy/zap-extensions#5205
- [x] https://www.zaproxy.org/docs/alerts/10055-9/ zaproxy/zap-extensions#5205
- [x] https://www.zaproxy.org/docs/alerts/10055-10/ zaproxy/zap-extensions#5205
- [x] https://www.zaproxy.org/docs/alerts/10055-11/ zaproxy/zap-extensions#5205
- [x] https://www.zaproxy.org/docs/alerts/10055-12/ zaproxy/zap-extensions#5205
- [x] https://www.zaproxy.org/docs/alerts/10058/ zaproxy/zap-extensions#5181 
- [x] https://www.zaproxy.org/docs/alerts/10096/ zaproxy/zap-extensions#5251
- [x] https://www.zaproxy.org/docs/alerts/10097/ zaproxy/zap-extensions#5251
- [x] https://www.zaproxy.org/docs/alerts/10101/
- [x] https://www.zaproxy.org/docs/alerts/10102/
- [x] https://www.zaproxy.org/docs/alerts/10105 zaproxy/zap-extensions#5261
- [x] https://www.zaproxy.org/docs/alerts/10202/ zaproxy/zap-extensions#5181 
- [x] https://www.zaproxy.org/docs/alerts/20012/ zaproxy/zap-extensions#5181 
- [x] https://www.zaproxy.org/docs/alerts/20014/ zaproxy/zap-extensions#5195
- [x] https://www.zaproxy.org/docs/alerts/20016/ zaproxy/zap-extensions#5291
- [x] https://www.zaproxy.org/docs/alerts/20017/ zaproxy/zap-extensions#5177
- [x] https://www.zaproxy.org/docs/alerts/20018/ zaproxy/zap-extensions#5177
- [x] https://www.zaproxy.org/docs/alerts/20019-1/ zaproxy/zap-extensions#5177 
- [x] https://www.zaproxy.org/docs/alerts/20019-2/ zaproxy/zap-extensions#5177
- [x] https://www.zaproxy.org/docs/alerts/20019-3/ zaproxy/zap-extensions#5177
- [x] https://www.zaproxy.org/docs/alerts/20019-4/ zaproxy/zap-extensions#5177
- [x] https://www.zaproxy.org/docs/alerts/30003/ zaproxy/zap-extensions#5329
- [x] https://www.zaproxy.org/docs/alerts/40003/ zaproxy/zap-extensions#5181
- [x] https://www.zaproxy.org/docs/alerts/40009/ zaproxy/zap-extensions#5229
- [x] https://www.zaproxy.org/docs/alerts/40012/ zaproxy/zap-extensions#5177
- [x] https://www.zaproxy.org/docs/alerts/40013/ zaproxy/zap-extensions#5262
- [x] https://www.zaproxy.org/docs/alerts/40014/ zaproxy/zap-extensions#5177
- [ ] https://www.zaproxy.org/docs/alerts/40015/ zaproxy/zap-extensions#5360
- [x] https://www.zaproxy.org/docs/alerts/40023/ - zaproxy/zap-extensions#5304
- [x] https://www.zaproxy.org/docs/alerts/40026/
- [x] https://www.zaproxy.org/docs/alerts/40031/ zaproxy/zap-extensions#4876
- [x] https://www.zaproxy.org/docs/alerts/40032/
- [x] https://www.zaproxy.org/docs/alerts/40044/ zaproxy/zap-extensions#5223
- [x] https://www.zaproxy.org/docs/alerts/90011/ zaproxy/zap-extensions#5201
- [x] https://www.zaproxy.org/docs/alerts/90019-1/ zaproxy/zap-extensions#5200
- [x] https://www.zaproxy.org/docs/alerts/90019-2/ zaproxy/zap-extensions#5200
- [x] https://www.zaproxy.org/docs/alerts/90020/ zaproxy/zap-extensions#5181
- [x] https://www.zaproxy.org/docs/alerts/90021/ zaproxy/zap-extensions#5177
- [x] https://www.zaproxy.org/docs/alerts/90023/ zaproxy/zap-extensions#5177
- [x] https://www.zaproxy.org/docs/alerts/90024/
- [x] https://www.zaproxy.org/docs/alerts/90025/ zaproxy/zap-extensions#5195
- [x] https://www.zaproxy.org/docs/alerts/90026/ - zaproxy/zap-extensions#5302
- [x] https://www.zaproxy.org/docs/alerts/90027/ zaproxy/zap-extensions#5177
- [x] https://www.zaproxy.org/docs/alerts/90028/ zaproxy/zap-extensions#5177
- [x] https://www.zaproxy.org/docs/alerts/90029/ - zaproxy/zap-extensions#5302
- [x] https://www.zaproxy.org/docs/alerts/90030/
- [x] https://www.zaproxy.org/docs/alerts/90033/ zaproxy/zap-extensions#5194

Note that some of the alerts may have been updated but not released - those can just be checked off.

If you fancy working on this the comment saying which ones you plan to update - just do a few at a time so that its easier to review and to leave plenty for other people 😉

**Comment by amitpanwar789** [comment]
@psiinon , i will like to work on some of this , after going through the code especially for https://www.zaproxy.org/docs/alerts/10019/
 https://www.zaproxy.org/docs/alerts/10021/
 i think we only need to change the message.properties file of respective alerts, am i right ?

**Comment by thc202** [comment]
Yes.

**Comment by kingthorin** [comment]
I've added a PR reference for those for which the Vulnerabilities.xml entry was adjusted but they still need examples and testing, so are not checked off (though maybe that's more 6119?).

**Comment by thc202** [comment]
IMO we should only check the ones that were already merged, and yes, the validation of refs should be left for other issue.

**Comment by 8linkz** [comment]
I would now work on https://www.zaproxy.org/docs/alerts/90019-2/

I will always edit this post when I finish or start the next one.

**Comment by thc202** [comment]
Better pick several and post a new comment, otherwise we will have to check the comment for edits (they don't raise notifications like new comments do).

**Comment by kingthorin** [comment]
Also if there are variants of a single alert it would be best to tackle them all at the same time. (Ex: Tackle 90019*)

**Comment by 8linkz** [comment]
i will work on:
https://www.zaproxy.org/docs/alerts/90011/
https://www.zaproxy.org/docs/alerts/20014/
https://www.zaproxy.org/docs/alerts/10035/

**Comment by thc202** [comment]
For 20014 please update the existing PR (if still open by then).

**Comment by 8linkz** [comment]
All the above done. General question: For some links, if you change them from HTTP to HTTPS, the link still works, but the certificate of the reference page is invalid because it is issued for the wrong domain (https://projects.webappsec.org/w/page/13246925/Fingerprinting)

Should the old reference be retained or replaced with a completely new one?

**Comment by kingthorin** [comment]
WASC is dead as far as I'm concerned so I'd suggest changing it to something else, or dropping it if you can't find something useful. When I was going through the vulnerabilities.xml changes I found that the OWASP CheetSheet project had good sources to replace WASC for a lot of things.

**Comment by 8linkz** [comment]
https://www.zaproxy.org/docs/alerts/3-1/ and https://www.zaproxy.org/docs/alerts/3-2/ 
are written 1 to 1 the same - shouldn't one of the two alerts be removed?

**Comment by psiinon** [comment]
Yeah, it does look like these should be the same type of alerts, even though the detection code is slightly different. This would require a code change.
Thoughts @thc202 @kingthorin ?

**Comment by kingthorin** [comment]
It becomes a bigger issue to drop or remember things. It could mess with people's alert filters.

I'd have to look at the code again to see the difference(s).

**Comment by kingthorin** [comment]
For my two cents leave it as-is for now.

**Comment by kingthorin** [comment]
I'm working through example alerts and refs in pscanrules over the weekend. I'll update the lists on both issues as I go.

**Comment by PariharAditya** [comment]
Hello, @psiinon 
It's Aditya again I would like to work on [this issue](https://www.zaproxy.org/docs/alerts/10050/)

**Comment by PariharAditya** [comment]
I'm working on 
 https://www.zaproxy.org/docs/alerts/40044/

**Comment by kingthorin** [comment]
Re: https://www.zaproxy.org/docs/alerts/10053/ I've checked it off as it's a deprecated rule.

**Comment by thc202** [comment]
It's not, now assigned to you.

**Comment by jay3393** [comment]
@thc202 Can I try [https://www.zaproxy.org/docs/alerts/40013/](https://www.zaproxy.org/docs/alerts/40013/)

**Comment by kingthorin** [comment]
Go for it!

**Comment by biplavoraon** [comment]
I would like to do  [ https://www.zaproxy.org/docs/alerts/40023/]( https://www.zaproxy.org/docs/alerts/40023/), [ https://www.zaproxy.org/docs/alerts/40031/]( https://www.zaproxy.org/docs/alerts/40031/) and [ https://www.zaproxy.org/docs/alerts/90027/]( https://www.zaproxy.org/docs/alerts/90027/).

**Comment by thc202** [comment]
There were some rules that were already using HTTPS but not yet checked, it should be updated now. (The WSDL had no references at all.)

**Comment by kingthorin** [comment]
Are we really down to the last one? 
Was this list generated programmatically? If so can someone double check?

**Comment by thc202** [comment]
In the website that was the last one using HTTP although there were some others not shown in the website that were still using HTTP (best is to search the `Messages.properties` files for the HTTP scheme).

**Comment by kingthorin** [comment]
Looks like just a few in pscanrules (I'll PR shortly):
- https://github.com/search?q=repo%3Azaproxy%2Fzap-extensions+path%3AaddOns%2Fpscanrules%2Fsrc%2Fmain%2Fresources%2Forg%2Fzaproxy%2Fzap%2Fextension%2Fpscanrules%2Fresources%2FMessages.properties+%22http%3A%22&type=code

---

- https://github.com/search?q=repo%3Azaproxy%2Fzap-extensions+path%3AaddOns%2Fascanrules%2Fsrc%2Fmain%2Fresources%2Forg%2Fzaproxy%2Fzap%2Fextension%2Fascanrules%2Fresources%2FMessages.properties+%22http%3A%22&type=code
- https://github.com/search?q=repo%3Azaproxy%2Fzap-extensions+path%3AaddOns%2FascanrulesBeta%2Fsrc%2Fmain%2Fresources%2Forg%2Fzaproxy%2Fzap%2Fextension%2FascanrulesBeta%2Fresources%2FMessages.properties+%22http%3A%22&type=code
-  https://github.com/search?q=repo%3Azaproxy%2Fzap-extensions+path%3AaddOns%2FascanrulesAlpha%2Fsrc%2Fmain%2Fresources%2Forg%2Fzaproxy%2Fzap%2Fextension%2FascanrulesAlpha%2Fresources%2FMessages.properties+%22http%3A%22&type=code

- https://github.com/search?q=repo%3Azaproxy%2Fzap-extensions+path%3AaddOns%2FpscanrulesBeta%2Fsrc%2Fmain%2Fresources%2Forg%2Fzaproxy%2Fzap%2Fextension%2FpscanrulesBeta%2Fresources%2FMessages.properties+%22http%3A%22&type=code
- https://github.com/search?q=repo%3Azaproxy%2Fzap-extensions+path%3AaddOns%2FpscanrulesAlpha%2Fsrc%2Fmain%2Fresources%2Forg%2Fzaproxy%2Fzap%2Fextension%2FpscanrulesAlpha%2Fresources%2FMessages.properties+%22http%3A%22&type=code

**Comment by thc202** [comment]
Those are examples though, not URLs that the user is expected to access.

**Comment by kingthorin** [comment]
Ya they all read fine being changed from my point of view.
