### ISSUE TITLE
No Way to Specify Custom 404

### ISSUE THREAD

**Issue by zapbot** [zaproxy/zaproxy#9]
```
What steps will reproduce the problem?
1. Scan something that returns custom a 302 to a custom 404 error message.

What is the expected output? What do you see instead?
Lots of False positives, especially when it comes to default files.

What version of the product are you using? On what operating system?
1.0.0. OS doesn't matter.

Please provide any additional information below.

```

> Original issue reported on code.google.com by `logicalgambit` on 2010-10-06 16:13:56
---

Part 1
======
- [x] Initial implementation - https://github.com/zaproxy/zaproxy/pull/3638
- [x] Analyzer fallback - https://github.com/zaproxy/zaproxy/pull/6194
- [x] UnitTests - https://github.com/zaproxy/zaproxy/pull/6232, https://github.com/zaproxy/zaproxy/pull/6245, https://github.com/zaproxy/zaproxy/pull/6310
- [x] Update User Guide / zap-core-help - https://github.com/zaproxy/zap-core-help/pull/335

Part 2
======
- [x] pscan rules adapted (When targeting 2.10.0) - https://github.com/zaproxy/zap-extensions/pull/2616, https://github.com/zaproxy/zap-extensions/pull/2627 https://github.com/zaproxy/zap-extensions/pull/2630
- [x] ascan rules adapted (When targeting 2.10.0) - https://github.com/zaproxy/zap-extensions/pull/2639 https://github.com/zaproxy/zap-extensions/pull/2642

**Comment by yhawke** [comment]
Dear all, I suffered the same trouble yesterday in a pentest when a nice programmer decided to use 200 and a page sying "this not exists" instead of 404 error... all the forced, svn, git, backup file plugins went crazy and the db became so big that everything has crashed!!!!
I don't know if someone is working on this, and I want to give my 2 cents.
Probably a good approach is using context, people could define custom 404 and 500 or other error messages using http response codes and regexes as you said before, then crawlers, active and passive plugins should use specific methods to check for a specific Response code (I don't agree for the isError, I think we can be more generic with isResponseCode(int Response code) then the implementation should apply the specific custom control or apply it to the Response Code directly).
But I think that a big improvement could be also to alert the user that a custom 404 exists. I saw that lot of scanners perform a check for an unexisting file and then, if the answer is 200, they alert the user that a custom error exists and the scanner hasn't been configured for this.
Sincerely I don't know how musch complex could be this implementation because I have any experience on ZAP contexts and extensions that can deal with them, but if this is simple to address I can give an hand...

**Comment by kingthorin** [comment]
I'd suggested isError because the solution shouldn't be limited to response codes. Since the issue is often that response codes are't always representative of content. Perhaps isCustomError or isCustomErrorResponse would be more indicative of the actual goal. I've been thinking about this lots lately and can see good arguments for both context and global implementation.

Trying to recognize and suggest setting custom error definitions might be harder. But definitely adds a user friendliness factor.

**Comment by yhawke** [comment]
Well, check it could be simple. We can send some probes for unexisting pages and if the response is 200 probably a custom 404 is in place. We can arise a dialog for the user to alert about the situation and he can abort and configure custom pages.
For the others I agree that it's impossible, but this is also less important. The real trouble are custom 404

**Comment by kingthorin** [comment]
Good point, trying to detect 404s would probably be a 80% solution, perhaps even more.

**Comment by thc202** [comment]
Active scanner is already doing that (or trying to), with `Analyser` class. [1]
It's also exposed to scanners through `AbstractPlugin.isFileExist(HttpMessage)` (which seems to be the opposite of `isError`).  [2]

[1] https://github.com/zaproxy/zaproxy/blob/55202a1d5becf6260ecb25cd3ebc49e271d477e8/src/org/parosproxy/paros/core/scanner/Analyser.java
[2] https://github.com/zaproxy/zaproxy/blob/55202a1d5becf6260ecb25cd3ebc49e271d477e8/src/org/parosproxy/paros/core/scanner/AbstractPlugin.java#L437

**Comment by psiinon** [comment]
We should document this much better - maybe an 'advanced a/pscan rules' guide?

**Comment by yhawke** [comment]
Well I did a look to the Analyzer, but it seems to check if a page exists or not checking also for a "not found" pattern inside the content... so it seems more suitable to active plugins that currently work on the HTTP Status code... but I don't think that this soultion is good enought because it's not localized and don't take in care all the possibilities... I think that give to the user a custom pattern is the best idea.
Then we can force 404 status for pages that give 200 but are custom pages, or use the same method you described before and change all the active plugins and the crawlers to do this.
Because the real trouble is related also to crawlers that maybe are following not existing links... 

My idea is instead to perform an initial probe before crawling to check for unexisting page (I se that Acunetix works in this way), then according to the result (HTTP OK for an unexisting page and maybe a pattern check in the body) alert the user that a custom 404 is probably in place (with evidence) and give to him the possibility to choice what to do next.
Then give to the user the possibility to go directly to the context panel, define a regex for the custom 404 (the default one could be the Analyzer existing pattern) and then we can approach control in one of the two models I described before (force status code or change all the plugins)....

**Comment by kingthorin** [comment]
I think changing the status code is a neat idea but I could see it shooting us in the foot later. We should minimize our impact on the traffic where/whenever possible. While it will be more work I think adapting all the scanners (as applicable) to leverage a check for custom errors is the superior solution.

As one example (and I'm sure there are others), some of the passive scanners check for client error (400 thru 499) and behave differently at certain attack thresholds. So if the app actually sends a 200 and then we alter it to 404, then analyze that response we might end up in a false negative or false positive condition.

**Comment by thc202** [comment]
The user guide will have to be updated to document the new functionality, added a task.
